<?php
// fichier de langues en anglais

// Homepage
define("_WELCOME","Welcome on <a href=\"#\" class=\"white\">nicolasmine.com</a>");

define("_MENU1_TITLE","Scripts");
define("_MENU2_TITLE","Who am I ?");
define("_MENU3_TITLE","Learn Python");
define("_MENU4_TITLE","News");
define("_MENU5_TITLE","Misc");

define("_MENU1_DESC","In this section, I will share with you some scripts I made on Jupyter Notebook with explainations. Unortunately, it won't present Codingame puzzles as most of inputs are provided every turns and depends on our previous output. You can nevertheless refer to my <a href=\"https://github.com/Coni63\" target=\"_blank\">Github</a> but not presented on Notebook");
define("_MENU2_DESC","Wants to know more about myself, take a look to my Resume");
define("_MENU3_DESC","In this section, I will make you discover some contents (websites, youtube channel, books) I found usefull to learn Python or Programming in general.");
define("_MENU4_DESC","On this section, I will share with you some articles on various information or news");
define("_MENU5_DESC","This section will be a repository of miscelleanous information (websites, twitter account). Be curious !");

// MISC

define("_TITLE_MISC", _MENU5_TITLE);
define("_HEADER_MISC", _MENU5_DESC);

define("_TITLE_AT", "Websites");
define("_TITLE_TWEET", "Twitter");
define("_TITLE_TWEET_2", "Tweet");
define("_TITLE_GITHUB", "Github");

define("_SECTION_AT", "Websites");
define("_SECTION_TWEET", "Twitter");
define("_SECTION_TWEET_2", "Tweet");
define("_SECTION_GITHUB", "Github");

?>