<?php
// fichier de langues en francais
 
// Homepage
define("_WELCOME","Bienvenue sur <a href=\"#\" class=\"white\">nicolasmine.com</a>");

define("_MENU1_TITLE","Scripts");
define("_MENU2_TITLE","Qui suis-je ?");
define("_MENU3_TITLE","Apprendre Python");
define("_MENU4_TITLE","News");
define("_MENU5_TITLE","Divers");

define("_MENU1_DESC","Dans cette section, je vous partagerai des scripts que j'ai faits sur Jupyter Notebook avec des explications. Cependant, je ne présenterais pas les puzzles de Codingame car les entrées dépendent souvent de la sortie précédente que l'on donne. Vous pouvez néanmoins vous référez à mon <a href=\"https://github.com/Coni63\" target=\"_blank\">Github</a> mais les scripts ne sont ni commentés ni sur Notebooks");
define("_MENU2_DESC","Envie d'en savoir plus sur moi, jetez un coup d'oeil à mon CV");
define("_MENU3_DESC","Dans cette section, je vous présenterai différents contenus que j'ai découvert en apprenant Python ou la programmation en générale.");
define("_MENU4_DESC","Dans cette section, je partagerai diverses articles sur des informations ou nouveautés.");
define("_MENU5_DESC","Dans cette section, je partagerai des informations diverses (sites web, compte twitter, etc...). Soyez curieux !");

// MISC

define("_TITLE_MISC", _MENU5_TITLE);
define("_HEADER_MISC", _MENU5_DESC);

define("_TITLE_AT", "Site Web");
define("_TITLE_TWEET", "Twitter");
define("_TITLE_TWEET_2", "Tweet");
define("_TITLE_GITHUB", "Github");

define("_SECTION_AT", "Site Web");
define("_SECTION_TWEET", "Twitter");
define("_SECTION_TWEET_2", "Tweet");
define("_SECTION_GITHUB", "Github");

?>