<?php
// fichier de langues en anglais

// Homepage
define("_WELCOME","Welcome on <a href=\"#\" class=\"white\">nicolasmine.com</a>");

define("_MENU1_TITLE","Scripts");
define("_MENU2_TITLE","Who am I ?");
define("_MENU3_TITLE","Learn Data Science");
define("_MENU4_TITLE","Tweets");
define("_MENU5_TITLE","Misc");
define("_MENU6_TITLE","Projects");

define("_MENU1_DESC","In this section, I will share with you some scripts I made on Jupyter Notebook with explainations. Unortunately, it won't present Codingame puzzles as most of inputs are provided every turns and depends on our previous output. You can nevertheless refer to my <a href=\"https://github.com/Coni63\" target=\"_blank\">Github</a> but not presented on Notebook");
define("_MENU2_DESC","Wants to know more about myself, take a look to my Resume");
define("_MENU3_DESC","In this section, I will make you discover some contents (websites, youtube channel, books) I found usefull to learn Python, Data Sciences, A.I. or Programming in general.");
define("_MENU4_DESC","Due to time restriction, the \"news\" section has been replaced by my twitter account for ML. On this, I share interesting tweets I found.");
define("_MENU5_DESC","This section will be a repository of miscelleanous information (websites, twitter account). Be curious !");
define("_MENU6_DESC","Wants to see some content of training's project or a bit bigger projects ? It's here ! ");

define("_VERSION","1.5.8");

define("_NEWS59_TITLE","Add a script (v1.5.8)");
define("_NEWS59_DESC", "Add a script about Quantum Toss Coin");
define("_NEWS59_DATE", "2019-04-21");

define("_NEWS58_TITLE","Add a script (v1.5.7)");
define("_NEWS58_DESC", "Add a script about a Facebook Friends's number");
define("_NEWS58_DATE", "2019-04-07");

define("_NEWS57_TITLE","Add a script (v1.5.6)");
define("_NEWS57_DESC", "Add a script about a Sudoku Sover");
define("_NEWS57_DATE", "2019-03-24");

define("_NEWS56_TITLE","Add a script (v1.5.5)");
define("_NEWS56_DESC", "Add a script about the centrifuge problem");
define("_NEWS56_DATE", "2019-03-10");

define("_NEWS55_TITLE","Add a notebook (v1.5.4)");
define("_NEWS55_DESC", "Add the notebook about Filter Decomposition");
define("_NEWS55_DATE", "2019-02-24");

define("_NEWS54_TITLE","Add a notebook (v1.5.3)");
define("_NEWS54_DESC", "Add the notebook about Minesweeper Bot");
define("_NEWS54_DATE", "2019-02-10");

define("_NEWS53_TITLE","Add a notebook (v1.5.2)");
define("_NEWS53_DESC", "Add the notebook about Multiple knapsack problem");
define("_NEWS53_DATE", "2019-01-27");

define("_NEWS52_TITLE","Add a notebook (v1.5.1)");
define("_NEWS52_DESC", "Add the notebook about Bayesian Networks and Markov chains");
define("_NEWS52_DATE", "2019-01-20");

define("_NEWS51_TITLE","General update + Add a Notebook (v1.5.0)");
define("_NEWS51_DESC", "Update of the website (resume, titles, content) and add a Notebook regaridng Poses Estimation");
define("_NEWS51_DATE", "2019-01-13");

define("_NEWS50_TITLE","Add a notebook (v1.4.31)");
define("_NEWS50_DESC", "Add Script done for Birthday Bot");
define("_NEWS50_DATE", "2019-01-06");

define("_NEWS49_TITLE","Add a notebook (v1.4.30)");
define("_NEWS49_DESC", "Add the notebook (4/4) about Momentum Trading");
define("_NEWS49_DATE", "2018-12-16");

define("_NEWS48_TITLE","Add a notebook (v1.4.29)");
define("_NEWS48_DESC", "Add the notebook (3/4) about Momentum Trading");
define("_NEWS48_DATE", "2018-12-09");

define("_NEWS47_TITLE","Add a notebook (v1.4.28)");
define("_NEWS47_DESC", "Add the notebook (2/4) about Momentum Trading");
define("_NEWS47_DATE", "2018-12-02");

define("_NEWS46_TITLE","Add a notebook (v1.4.27)");
define("_NEWS46_DESC", "Add the notebook (1/4) about Momentum Trading");
define("_NEWS46_DATE", "2018-11-25");

define("_NEWS45_TITLE","Add a notebook (v1.4.26)");
define("_NEWS45_DESC", "Add a presentation of Proximal Policy optimization on Cartpole");
define("_NEWS45_DATE", "2018-11-18");

define("_NEWS44_TITLE","Add a notebook (v1.4.25)");
define("_NEWS44_DESC", "Add a presentation of Policy Gradient model on Cartpole");
define("_NEWS44_DATE", "2018-11-11");

define("_NEWS43_TITLE","Add a notebook (v1.4.24)");
define("_NEWS43_DESC", "Add a notebook about CPU vs GPU in Conway's Game of Life");
define("_NEWS43_DATE", "2018-11-04");

define("_NEWS42_TITLE","Multiple adds (v1.4.23)");
define("_NEWS42_DESC", "Add a notebook about 2 librairies, 2 twitter accounts and a youtube channel");
define("_NEWS42_DATE", "2018-10-28");

define("_NEWS41_TITLE","Add a script (v1.4.22)");
define("_NEWS41_DESC", "Add a script with the discovery of Deep-Q Networks");
define("_NEWS41_DATE", "2018-10-07");

define("_NEWS40_TITLE","Add a script (v1.4.21)");
define("_NEWS40_DESC", "Add a script regarding classification of recipes based on ingredients");
define("_NEWS40_DATE", "2018-09-10");

define("_NEWS39_TITLE","Add a script, a twitter account and a youtube channel (v1.4.20)");
define("_NEWS39_DESC", "Add a Notebook regarding Q-Learning, the twitter account of DeepMind and the channel of Arxvi Insight");
define("_NEWS39_DATE", "2018-09-02");

define("_NEWS38_TITLE","Add a script (v1.4.19)");
define("_NEWS38_DESC", "Add a Notebook regarding the exploration of Madrid's Air Quality");
define("_NEWS38_DATE", "2018-08-26");

define("_NEWS37_TITLE","Adding 2 small java projects (v1.4.18)");
define("_NEWS37_DESC", "Add a Java project regarding fractals and 1 regarding communication between android and java with bluetooth.");
define("_NEWS37_DATE", "2018-08-20");

define("_NEWS36_TITLE","Adding a second Java script (v1.4.17)");
define("_NEWS36_DESC", "Add a new script in Java regarding the search of a code based on the number of correct digits");
define("_NEWS36_DATE", "2018-08-12");

define("_NEWS35_TITLE","Add a script (v1.4.16)");
define("_NEWS35_DESC", "Add a script to reproduce the results of a paper published on ArXiv about the classification of ECG");
define("_NEWS35_DATE", "2018-08-05");

define("_NEWS34_TITLE","Add a Java project in script (v1.4.15)");
define("_NEWS34_DESC", "Add a result of a script done in Java regarding genetic algorithm & PID control loop response set-up");
define("_NEWS34_DATE", "2018-07-29");

define("_NEWS33_TITLE","Add a script (v1.4.14)");
define("_NEWS33_DESC", "Add a script regarding use of Programming Languages in CodingGame competition");
define("_NEWS33_DATE", "2018-07-22");

define("_NEWS32_TITLE","Add a script (v1.4.13)");
define("_NEWS32_DESC", "Add a script regarding a solver of Taquin");
define("_NEWS32_DATE", "2018-07-16");

define("_NEWS31_TITLE","Add script (v1.4.12)");
define("_NEWS31_DESC", "Adding a script of sentiment analysis on tweets during the France vs Argentina match");
define("_NEWS31_DATE", "05/07/2018");

define("_NEWS30_TITLE","Add (2+1) scripts (v1.4.11)");
define("_NEWS30_DESC", "Add a script concerning the regression on circular datas and 2 scripts on the sentiments analysis");
define("_NEWS30_DATE", "2018-06-30");

define("_NEWS29_TITLE","Add a script and a book (v1.4.10)");
define("_NEWS29_DESC", "Add a script on the audio classification from a Kaggle competition and a book in the section \"Learn Python\"");
define("_NEWS29_DATE", "2018-06-18");

define("_NEWS28_TITLE","Add 2 scripts (v1.4.9)");
define("_NEWS28_DESC", "Add 2 scripts regarding classification on FMA dataset using meta data.");
define("_NEWS28_DATE", "2018-05-26");

define("_NEWS27_TITLE","Add a script (v1.4.8)");
define("_NEWS27_DESC", "Add a second script regarding audio segmentation on FMA dataset");
define("_NEWS27_DATE", "2018-05-16");

define("_NEWS26_TITLE","Add a script (v1.4.7)");
define("_NEWS26_DESC", "Add a second scriptregarding audio classification on FMA dataset");
define("_NEWS26_DATE", "2018-05-10");

define("_NEWS25_TITLE","Add a script (v1.4.6)");
define("_NEWS25_DESC", "Add a script regarding audio classification.");
define("_NEWS25_DATE", "2018-05-02");

define("_NEWS24_TITLE","Add 2 Scripts (v1.4.5)");
define("_NEWS24_DESC", "Add a script about DeepDream and one with an exploration with R");
define("_NEWS24_DATE", "2018-04-28");

define("_NEWS23_TITLE","Add a Script (v1.4.4)");
define("_NEWS23_DESC", "Add a script about Neuro-Evolution in Reinforcement Learning");
define("_NEWS23_DATE", "2018-04-15");

define("_NEWS22_TITLE","Adding 3 projects (v1.4.3)");
define("_NEWS22_DESC", "Add 3 project (Customer Segmentation V2, DOSNES and movie Explorer)");
define("_NEWS22_DATE", "2018-04-09");

define("_NEWS21_TITLE","Adding a Script and a site in Misc section (v1.4.2)");
define("_NEWS21_DESC", "Added a link to Variance Explained and a notebook on the classification of a subset of QuickDraw");
define("_NEWS21_DATE", "2018-03-17");

define("_NEWS20_TITLE","UI changes, add a new notebook and hyperlinks (v1.4.1)");
define("_NEWS20_DESC", "Few UI points have been improved, a new version of the double pendulum with with RNN is uploaded and some new hyperlinks (DataCamp, websites, ...)");
define("_NEWS20_DATE", "2018-03-10");

define("_NEWS19_TITLE","Section news replaced by tweets (v1.4.0)");
define("_NEWS19_DESC", "Due to time restriction, I replaced the section news by tweets. News will be re-tweeted more often that I was writing news.");
define("_NEWS19_DATE", "2018-02-24");

define("_NEWS18_TITLE","Add 3 Notebook in Scripts sections (v1.3.2)");
define("_NEWS18_DESC", "Add notebooks regarding Double Pendulum, Test of FBProphet for timeseries and a test of UMAP to visualize clustering of articles from a shop");
define("_NEWS18_DATE", "2018-02-22");

define("_NEWS17_TITLE","Add projects from OpenClassrooms's Master (v1.3.1)");
define("_NEWS17_DESC", "All 8 projects have been added with report/powerpoints and a summary (in French)");
define("_NEWS17_DATE", "2018-02-04");

define("_NEWS16_TITLE","Add a presentation of Master's project and update of \"About me\" Section (v1.3)");
define("_NEWS16_DESC", "A new section has been added in order to share with you my Data Scientist's projects. Adding 2 books in\"Learn Python\"'s section ");
define("_NEWS16_DATE", "2018-01-02");

define("_NEWS15_TITLE","Add my feed twitter into Misc. (v1.2.3)");
define("_NEWS15_DESC", "During the training, News I used to share every week will be replaced by my tweeter's timeline");
define("_NEWS15_DATE", "2017-11-10");

define("_NEWS14_TITLE","Add content (v1.2.2)");
define("_NEWS14_DESC", "Modified 1 script (Reber), add a news and Add formation");
define("_NEWS14_DATE", "2017-11-01");

define("_NEWS13_TITLE","Add content (v1.2.1)");
define("_NEWS13_DESC", "Add news, Misc. and a script");
define("_NEWS13_DATE", "2017-10-28");

define("_NEWS12_TITLE","Several changes (v1.2.0)");
define("_NEWS12_DESC", "<li>5 news</li><li>1 script</li><li>1 news misc. pages</li><li>modification of website structure</li>");
define("_NEWS12_DATE", "2017-10-22");

define("_NEWS11_TITLE","Add some news (v1.1.8)");
define("_NEWS11_DESC", "4 news added");
define("_NEWS11_DATE", "2017-10-12");

define("_NEWS10_TITLE","Add some news (v1.1.7)");
define("_NEWS10_DESC", "4 news added");
define("_NEWS10_DATE", "2017-10-01");

define("_NEWS9_TITLE","Adding some content (v1.1.6)");
define("_NEWS9_DESC", "Adding a script regarding credit card fraud detection, update on my resume section, adding a book and a youtube channel");
define("_NEWS9_DATE", "2017-09-19");

define("_NEWS8_TITLE","Adding a script (v1.1.5)");
define("_NEWS8_DESC", "Adding a script regarding the estimation of a rent price");
define("_NEWS8_DATE", "2017-09-10");

define("_NEWS7_TITLE","Adding a script (v1.1.4)");
define("_NEWS7_DESC", "Adding a script regarding the exploration of Neural Network");
define("_NEWS7_DATE","2017-08-23");

define("_NEWS6_TITLE","Adding some contents (v1.1.3)");
define("_NEWS6_DESC", "Adding some scripts and a News. Fix encoding on mail function");
define("_NEWS6_DATE","2017-08-19");

define("_NEWS5_TITLE","Adding some contents (v1.1.2)");
define("_NEWS5_DESC", "Adding a website in \"Learn Python\" section and some scripts");
define("_NEWS5_DATE","2017-08-16");

define("_NEWS4_TITLE","Update on UI and Settings Apache (v1.1.1)");
define("_NEWS4_DESC", "Improvement of the UI and fixed issue with cache");
define("_NEWS4_DATE","2017-08-14");

define("_NEWS3_TITLE","UI improvement and Multilanguage support added (v1.1.0)");
define("_NEWS3_DESC", "Change Structure and create English and French Langages <br/> Some UI changes");
define("_NEWS3_DATE","2017-08-13");

define("_NEWS2_TITLE","Bugs fixing and Improvements (v1.0.1)");
define("_NEWS2_DESC", "Correct some issues, improve code to be faster");
define("_NEWS2_DATE","2017-08-09");

define("_NEWS1_TITLE","Original Release (v1.0)");
define("_NEWS1_DESC", "Initial release of <a href=\"#\">nicolasmine.com</a>");
define("_NEWS1_DATE","2017-08-08");

?>