<?php
// fichier de langues en francais
 
// Homepage
define("_WELCOME","Bienvenue sur <a href=\"#\" class=\"white\">nicolasmine.com</a>");

define("_MENU1_TITLE","Scripts");
define("_MENU2_TITLE","Qui suis-je ?");
define("_MENU3_TITLE","Apprendre Python");
define("_MENU4_TITLE","Tweets");
define("_MENU5_TITLE","Divers");
define("_MENU6_TITLE","Projets");

define("_MENU1_DESC","Dans cette section, je vous partagerai des scripts que j'ai faits sur Jupyter Notebook avec des explications. Cependant, je ne présenterais pas les puzzles de Codingame car les entrées dépendent souvent de la sortie précédente que l'on donne. Vous pouvez néanmoins vous référez à mon <a href=\"https://github.com/Coni63\" target=\"_blank\">Github</a> mais les scripts ne sont ni commentés ni sur Notebooks");
define("_MENU2_DESC","Envie d'en savoir plus sur moi, jetez un coup d'oeil à mon CV");
define("_MENU3_DESC","Dans cette section, je vous présenterai différents contenus que j'ai découvert en apprenant Python, la Data Science, l'I.A. ou la programmation en générale.");
define("_MENU4_DESC","Pour des raisons de temps, la section \"news\" a été remplacé par mon compte twitter sur le ML. Sur celui-ci, je partage différents tweet interessant que je trouve sur le domaine.");
define("_MENU5_DESC","Dans cette section, je partagerai des informations diverses (sites web, compte twitter, etc...). Soyez curieux !");
define("_MENU6_DESC","Envie de voir un résumé des différents projets du Master ? C'est ici ! (En construction, le contenu sera ajouté au fur et à mesure).");

define("_VERSION","1.4.3");

define("_NEWS22_TITLE","Ajout de 3 projets (v1.4.3)");
define("_NEWS22_DESC", "Ajout des 3 projets (Segmentation des clients V2, DOSNES et movie Explorer)");
define("_NEWS22_DATE", "09/04/2018");

define("_NEWS21_TITLE","Ajout d'un Script et d'un site dans Divers (v1.4.2)");
define("_NEWS21_DESC", "Ajout d'un lien vers Variance Explained et d'un notebook sur la classification d'un sous dataset de QuickDraw");
define("_NEWS21_DATE", "17/03/2018");

define("_NEWS20_TITLE","Modif UI, ajout notebook et liens (v1.4.1)");
define("_NEWS20_DESC", "Quelques points de l'interface ont été améliorés, un nouveau script ajouté (amélioration du double pendule avec RNN) ainsi que différents nouveaux liens (DataCamp, sites, etc...)");
define("_NEWS20_DATE", "10/03/2018");

define("_NEWS19_TITLE","Section news replacée par des tweets (v1.4.0)");
define("_NEWS19_DESC", "Pour des raisons de temps, la section News a été remplacée par des tweets. Cela permettra un partage plus fréquent de nouveautés.");
define("_NEWS19_DATE", "24/02/2018");

define("_NEWS18_TITLE","Ajout de 3 Notebook dans la partie Script (v1.3.2)");
define("_NEWS18_DESC", "Ajout de notebook sur la simulation d'un Double Pendule, un test de FBProphet sur un dataset temporel et un test de UMAP pour visualiser le clustering d'articles d'un magasin");
define("_NEWS18_DATE", "22/02/2018");

define("_NEWS17_TITLE","Ajout des projets du Master OpenClassrooms (v1.3.1)");
define("_NEWS17_DESC", "Les 8 projets du Master OpenClassrooms ont été ajoutés avec le rapport/présentation et fiche de synthèse");
define("_NEWS17_DATE", "04/02/2018");

define("_NEWS16_TITLE","Ajout des projets du Master et de la page résumé (v1.3)");
define("_NEWS16_DESC", "Une nouvelle section a été ajoutée afin de vous présenter les différents projets faits pour le Master de Data Scientist. Ajout de 2 livres dans la section\"Apprendre Python\" ");
define("_NEWS16_DATE", "02/01/2018");

define("_NEWS15_TITLE","Ajout de ma timeline twitter dans Divers (v1.2.3)");
define("_NEWS15_DESC", "Durant la formation, les news vont être remplacées pour une timeline twitter que vous trouverez dans Divers.");
define("_NEWS15_DATE", "10/11/2017");

define("_NEWS14_TITLE","Ajout de contenu (v1.2.2)");
define("_NEWS14_DESC", "Modification d'un script (Reber), ajout d'une nouveauté et ajout d'une formation");
define("_NEWS14_DATE", "01/11/2017");

define("_NEWS13_TITLE","Ajout de contenu (v1.2.1)");
define("_NEWS13_DESC", "Ajout de news, de divers contenus et un script");
define("_NEWS13_DATE", "28/11/2017");

define("_NEWS12_TITLE","Multiples changement (v1.2.0)");
define("_NEWS12_DESC", "<li>5 news</li><li>1 script</li><li>1 nouvelle page de points divers</li><li>refonte de la structure du site</li>");
define("_NEWS12_DATE", "22/10/2017");

define("_NEWS11_TITLE","Ajout de news (v1.1.8)");
define("_NEWS11_DESC", "Ajout de 4 news");
define("_NEWS11_DATE", "12/10/2017");

define("_NEWS10_TITLE","Ajout de news (v1.1.7)");
define("_NEWS10_DESC", "Ajout de 4 news");
define("_NEWS10_DATE", "01/10/2017");

define("_NEWS9_TITLE","Ajout de contenu (v1.1.6)");
define("_NEWS9_DESC", "Ajout d'un script sur la detection de fraud sur des carte de crédits, mise à jour de mon CV, ajout d'un livre ainsi que d'une chaine Youtube");
define("_NEWS9_DATE", "19/09/2017");

define("_NEWS8_TITLE","Ajout d'un script (v1.1.5)");
define("_NEWS8_DESC", "Ajout d'un script sur la mise en place d'un model de prix de loyer");
define("_NEWS8_DATE", "10/09/2017");

define("_NEWS7_TITLE","Ajout d'un script (v1.1.4)");
define("_NEWS7_DESC", "Ajout d'un script sur l'exploration de Réseaux de Neuronnes");
define("_NEWS7_DATE", "23/08/2017");

define("_NEWS6_TITLE","Ajout de contenu (v1.1.3)");
define("_NEWS6_DESC", "Ajout de plusieurs scripts et d'une News. Correction d'un bug d'encodage sur la fonction mail.");
define("_NEWS6_DATE","19/08/2017");

define("_NEWS5_TITLE","Ajout de contenu (v1.1.2)");
define("_NEWS5_DESC", "Ajout d'un site dans la section \"Apprendre Python\". Ajout de plusieurs scripts");
define("_NEWS5_DATE","16/08/2017");

define("_NEWS4_TITLE","Modification d'UI et Réglages Apache (v1.1.1)");
define("_NEWS4_DESC", "Amélioration de l'UI et correction de problèmes avec le cache");
define("_NEWS4_DATE","14/08/2017");

define("_NEWS3_TITLE","Modification d'UI et ajout du Multilangues (v1.1.0)");
define("_NEWS3_DESC", "Modification de la structure du site pour un support Français et Anglais <br/> Changement de l'interface");
define("_NEWS3_DATE","13/08/2017");

define("_NEWS2_TITLE","Resolutions de bug et Améliorations (v1.0.1)");
define("_NEWS2_DESC", "Correction de bugs et amélioration du code pour un chargement plus rapide");
define("_NEWS2_DATE","09/08/2017");

define("_NEWS1_TITLE","Mise en ligne (v1.0)");
define("_NEWS1_DESC", "Première mise en ligne de <a href=\"#\">nicolasmine.com</a>");
define("_NEWS1_DATE","08/08/2017");

?>