<?php
// fichier de langues en francais
 
// Homepage
define("_WELCOME","Bienvenue sur <a href=\"#\" class=\"white\">nicolasmine.com</a>");

define("_MENU1_TITLE","Scripts");
define("_MENU2_TITLE","Qui suis-je ?");
define("_MENU3_TITLE","Apprendre La Data Science");
define("_MENU4_TITLE","Tweets");
define("_MENU5_TITLE","Divers");
define("_MENU6_TITLE","Projets");

define("_MENU1_DESC","Dans cette section, je vous partagerai des scripts que j'ai faits sur Jupyter Notebook avec des explications. Cependant, je ne présenterais pas les puzzles de Codingame car les entrées dépendent souvent de la sortie précédente que l'on donne. Vous pouvez néanmoins vous référez à mon <a href=\"https://github.com/Coni63\" target=\"_blank\">Github</a> mais les scripts ne sont ni commentés ni sur Notebooks");
define("_MENU2_DESC","Envie d'en savoir plus sur moi, jetez un coup d'oeil à mon CV");
define("_MENU3_DESC","Dans cette section, je vous présenterai différents contenus que j'ai découvert en apprenant Python, la Data Science, l'I.A. ou la programmation en générale.");
define("_MENU4_DESC","Pour des raisons de temps, la section \"news\" a été remplacé par mon compte twitter sur le ML. Sur celui-ci, je partage différents tweet interessant que je trouve sur le domaine.");
define("_MENU5_DESC","Dans cette section, je partagerai des informations diverses (sites web, compte twitter, etc...). Soyez curieux !");
define("_MENU6_DESC","Envie de voir un résumé des différents projets du Master ou des projets un peu plus importants ? C'est ici !");

define("_VERSION","1.5.17");

define("_NEWS68_TITLE","Ajout d'un script (v1.5.17)");
define("_NEWS68_DESC", "Ajout d'une visualisation en p5.js sur le Ray Marching");
define("_NEWS68_DATE", "01/09/2019");

define("_NEWS67_TITLE","Ajout d'un script (v1.5.16)");
define("_NEWS67_DESC", "Ajout d'un second script sur la Classification avec Seam Carving");
define("_NEWS67_DATE", "25/08/2019");

define("_NEWS66_TITLE","Ajout d'un script (v1.5.15)");
define("_NEWS66_DESC", "Ajout d'un script sur la Classification avec Seam Carving");
define("_NEWS66_DATE", "04/08/2019");

define("_NEWS65_TITLE","Ajout d'un script  (v1.5.14)");
define("_NEWS65_DESC", "Ajout d'un script sur la Class Activation Map");
define("_NEWS65_DATE", "21/07/2019");

define("_NEWS64_TITLE","Ajout d'un script  (v1.5.13)");
define("_NEWS64_DESC", "Ajout d'un script sur le Seam Carving");
define("_NEWS64_DATE", "07/07/2019");

define("_NEWS63_TITLE","Ajout d'un script  (v1.5.12)");
define("_NEWS63_DESC", "Ajout d'un script sur l'attaque sur le Logarithme Discret");
define("_NEWS63_DATE", "23/06/2019");

define("_NEWS62_TITLE","Ajout d'un script  (v1.5.11)");
define("_NEWS62_DESC", "Ajout d'un script sur le chiffrement par bloc et le Triple DES");
define("_NEWS62_DATE", "09/06/2019");

define("_NEWS61_TITLE","Ajout d'un script (v1.5.10)");
define("_NEWS61_DESC", "Ajout d'un script sur la cryptographie sur les Courbes Elliptiques");
define("_NEWS61_DATE", "19/05/2019");

define("_NEWS60_TITLE","Ajout d'un script et correction d'un bug (v1.5.9)");
define("_NEWS60_DESC", "Ajout d'un script sur le RSA et correction d'une erreur avec une description manquante.");
define("_NEWS60_DATE", "05/05/2019");

define("_NEWS59_TITLE","Ajout d'un script (v1.5.8)");
define("_NEWS59_DESC", "Ajout d'un script sur le jeu du pile ou face quantique");
define("_NEWS59_DATE", "21/04/2019");

define("_NEWS58_TITLE","Ajout d'un script (v1.5.7)");
define("_NEWS58_DESC", "Ajout d'un script sur le nombre d'amis Facebook");
define("_NEWS58_DATE", "07/04/2019");

define("_NEWS57_TITLE","Ajout d'un script (v1.5.6)");
define("_NEWS57_DESC", "Ajout d'un script sur la resolution de Sudoku");
define("_NEWS57_DATE", "24/03/2019");

define("_NEWS56_TITLE","Ajout d'un script (v1.5.5)");
define("_NEWS56_DESC", "Ajout d'un script sur le problème de la centrifuge");
define("_NEWS56_DATE", "10/03/2019");

define("_NEWS55_TITLE","Ajout d'un script (v1.5.4)");
define("_NEWS55_DESC", "Ajout d'un notebook sur la décomposition de filtres");
define("_NEWS55_DATE", "24/02/2019");

define("_NEWS54_TITLE","Ajout d'un script (v1.5.3)");
define("_NEWS54_DESC", "Ajout d'un notebook sur un bot pour jouer au Démineur");
define("_NEWS54_DATE", "10/02/2019");

define("_NEWS53_TITLE","Ajout d'un script (v1.5.2)");
define("_NEWS53_DESC", "Ajout d'un notebook sur le Problème du sac à dos multiple.");
define("_NEWS53_DATE", "27/01/2019");

define("_NEWS52_TITLE","Ajout d'un script (v1.5.1)");
define("_NEWS52_DESC", "Ajout d'un notebook sur les réseaux Bayesiens et les chaines de Markov");
define("_NEWS52_DATE", "20/01/2019");

define("_NEWS51_TITLE","Mise à jour globale + Ajout Notebook (v1.5.0)");
define("_NEWS51_DESC", "Mise à jour du site (CV, titres, contenu) et ajout d'un script concernant l'estimation de positions");
define("_NEWS51_DATE", "13/01/2019");

define("_NEWS50_TITLE","Ajout d'un script (v1.4.31)");
define("_NEWS50_DESC", "Ajout des scripts concernant le Birthday Bot");
define("_NEWS50_DATE", "06/01/2019");

define("_NEWS49_TITLE","Ajout d'un script (v1.4.30)");
define("_NEWS49_DESC", "Ajout d'un notebook (4/4) sur le Momentum Trading ");
define("_NEWS49_DATE", "16/12/2018");

define("_NEWS48_TITLE","Ajout d'un script (v1.4.29)");
define("_NEWS48_DESC", "Ajout d'un notebook (3/4) sur le Momentum Trading ");
define("_NEWS48_DATE", "09/12/2018");

define("_NEWS47_TITLE","Ajout d'un script (v1.4.28)");
define("_NEWS47_DESC", "Ajout d'un notebook (2/4) sur le Momentum Trading ");
define("_NEWS47_DATE", "02/12/2018");

define("_NEWS46_TITLE","Ajout d'un script (v1.4.27)");
define("_NEWS46_DESC", "Ajout d'un notebook (1/4) sur le Momentum Trading ");
define("_NEWS46_DATE", "25/11/2018");

define("_NEWS45_TITLE","Ajout d'un script (v1.4.26)");
define("_NEWS45_DESC", "Ajout d'une présentation du \"Proximal Policy optimization\" sur l'environnement cartpole ");
define("_NEWS45_DATE", "18/11/2018");

define("_NEWS44_TITLE","Ajout d'un script (v1.4.25)");
define("_NEWS44_DESC", "Ajout d'une présentation du \"Policy Gradient\" sur l'environnement cartpole ");
define("_NEWS44_DATE", "11/11/2018");

define("_NEWS43_TITLE","Ajout d'un script (v1.4.24)");
define("_NEWS43_DESC", "Ajout d'un notebook comparant le CPU vs GPU pour le Jeu de la vie de Conway");
define("_NEWS43_DATE", "04/11/2018");

define("_NEWS42_TITLE","Multiple ajouts (v1.4.23)");
define("_NEWS42_DESC", "Ajout d'un notebook sur 2 librairies, 2 comptes twitter et une chaîne youtube");
define("_NEWS42_DATE", "28/10/2018");

define("_NEWS41_TITLE","Ajout d'un script (v1.4.22)");
define("_NEWS41_DESC", "Ajout d'un Notebook avec la decouverte des Deep-Q Networks");
define("_NEWS41_DATE", "07/10/2018");

define("_NEWS40_TITLE","Ajout d'un script (v1.4.21)");
define("_NEWS40_DESC", "Ajout d'un Notebook concernant la classification de recette en fonction des ingrédients.");
define("_NEWS40_DATE", "10/09/2018");

define("_NEWS39_TITLE","Ajout d'un script, un compte twitter et une chaîne youtube (v1.4.20)");
define("_NEWS39_DESC", "Ajout d'un Notebook à propos du Q-Learning, le compte twitter de DeepMind et une chaine youtube de Arxiv Insight");
define("_NEWS39_DATE", "02/09/2018");

define("_NEWS38_TITLE","Ajout d'un script (v1.4.19)");
define("_NEWS38_DESC", "Ajout d'un Notebook concernant l'exploration de la qualité de l'air à Madrid");
define("_NEWS38_DATE", "26/08/2018");

define("_NEWS37_TITLE","Ajout de 2 petits scripts (v1.4.18)");
define("_NEWS37_DESC", "Ajout d'un projet en Java sur les fractales et un second à propos de la communication entre android et Java avec le bluetooth.");
define("_NEWS37_DATE", "20/08/2018");

define("_NEWS36_TITLE","Ajout d'un second script Java (v1.4.17)");
define("_NEWS36_DESC", "Ajout d'un nouveau script en Java concernant la recherche d'un code basé sur le nombre de digits justes");
define("_NEWS36_DATE", "12/08/2018");

define("_NEWS35_TITLE","Ajout d'un script (v1.4.16)");
define("_NEWS35_DESC", "Ajout d'un script pour reproduire les resultats d'un papier publié sur ArXiv à propos de la classification d'electrocardiogrammes");
define("_NEWS35_DATE", "05/08/2018");

define("_NEWS34_TITLE","Ajout de mon 1er projet en Java (v1.4.15)");
define("_NEWS34_DESC", "Ajout d'un script fait en Java concernant les algorithmes génétiques et l'asservissement d'un systeme avec un PID");
define("_NEWS34_DATE", "29/07/2018");

define("_NEWS33_TITLE","Ajout d'un script (v1.4.14)");
define("_NEWS33_DESC", "Ajout d'un script sur l'utilisation des langages de programmation lors des compétitions sur Codingame");
define("_NEWS33_DATE", "22/07/2018");

define("_NEWS32_TITLE","Ajout d'un script (v1.4.13)");
define("_NEWS32_DESC", "Ajout d'un script sur un solveur du jeu du taquin");
define("_NEWS32_DATE", "16/07/2018");

define("_NEWS31_TITLE","Ajout d'un script (v1.4.12)");
define("_NEWS31_DESC", "Ajout d'un script sur l'analyse des sentiments sur des tweet durant le match France vs Argentine");
define("_NEWS31_DATE", "05/07/2018");

define("_NEWS30_TITLE","Ajout de (2+1) scripts (v1.4.11)");
define("_NEWS30_DESC", "Ajout d'un script concernant la regression sur un cercle et 2 scripts sur l'analyse de sentiments");
define("_NEWS30_DATE", "30/06/2018");

define("_NEWS29_TITLE","Ajout d'un script et d'un livre (v1.4.10)");
define("_NEWS29_DESC", "Ajout d'un script sur la classification audio issue d'une compétition Kaggle et d'un livre dans la section \"Apprendre Python\"");
define("_NEWS29_DATE", "18/06/2018");

define("_NEWS28_TITLE","Ajout de 2 Scripts (v1.4.9)");
define("_NEWS28_DESC", "Ajout de 2 Scripts à propos de la classification sur le dataset FMA en utilisant les meta data.");
define("_NEWS28_DATE", "26/05/2018");

define("_NEWS27_TITLE","Ajout d'un script (v1.4.8)");
define("_NEWS27_DESC", "Ajout d'un second script concernant la segmentation audio sur le dataset FMA");
define("_NEWS27_DATE", "16/05/2018");

define("_NEWS26_TITLE","Ajout d'un script (v1.4.7)");
define("_NEWS26_DESC", "Ajout d'un second script concernant la classification audio sur le dataset FMA");
define("_NEWS26_DATE", "10/05/2018");

define("_NEWS25_TITLE","Ajout d'un script (v1.4.6)");
define("_NEWS25_DESC", "Ajout d'un script concernant la classification audio");
define("_NEWS25_DATE", "02/05/2018");

define("_NEWS24_TITLE","Ajout de 2 Scripts (v1.4.5)");
define("_NEWS24_DESC", "Ajout de 2 scripts (DeepDream ainsi qu'une exploration d'un dataset avec R");
define("_NEWS24_DATE", "28/04/2018");

define("_NEWS23_TITLE","Ajout d'un script (v1.4.4)");
define("_NEWS23_DESC", "Ajout d'un script sur la Neuro-Evolution en Apprentissage par Renforcement");
define("_NEWS23_DATE", "15/04/2018");

define("_NEWS22_TITLE","Ajout de 3 projets (v1.4.3)");
define("_NEWS22_DESC", "Ajout des 3 projets (Segmentation des clients V2, DOSNES et movie Explorer)");
define("_NEWS22_DATE", "09/04/2018");

define("_NEWS21_TITLE","Ajout d'un Script et d'un site dans Divers (v1.4.2)");
define("_NEWS21_DESC", "Ajout d'un lien vers Variance Explained et d'un notebook sur la classification d'un sous dataset de QuickDraw");
define("_NEWS21_DATE", "17/03/2018");

define("_NEWS20_TITLE","Modif UI, ajout notebook et liens (v1.4.1)");
define("_NEWS20_DESC", "Quelques points de l'interface ont été améliorés, un nouveau script ajouté (amélioration du double pendule avec RNN) ainsi que différents nouveaux liens (DataCamp, sites, etc...)");
define("_NEWS20_DATE", "10/03/2018");

define("_NEWS19_TITLE","Section news replacée par des tweets (v1.4.0)");
define("_NEWS19_DESC", "Pour des raisons de temps, la section News a été remplacée par des tweets. Cela permettra un partage plus fréquent de nouveautés.");
define("_NEWS19_DATE", "24/02/2018");

define("_NEWS18_TITLE","Ajout de 3 Notebook dans la partie Script (v1.3.2)");
define("_NEWS18_DESC", "Ajout de notebook sur la simulation d'un Double Pendule, un test de FBProphet sur un dataset temporel et un test de UMAP pour visualiser le clustering d'articles d'un magasin");
define("_NEWS18_DATE", "22/02/2018");

define("_NEWS17_TITLE","Ajout des projets du Master OpenClassrooms (v1.3.1)");
define("_NEWS17_DESC", "Les 8 projets du Master OpenClassrooms ont été ajoutés avec le rapport/présentation et fiche de synthèse");
define("_NEWS17_DATE", "04/02/2018");

define("_NEWS16_TITLE","Ajout des projets du Master et de la page résumé (v1.3)");
define("_NEWS16_DESC", "Une nouvelle section a été ajoutée afin de vous présenter les différents projets faits pour le Master de Data Scientist. Ajout de 2 livres dans la section\"Apprendre Python\" ");
define("_NEWS16_DATE", "02/01/2018");

define("_NEWS15_TITLE","Ajout de ma timeline twitter dans Divers (v1.2.3)");
define("_NEWS15_DESC", "Durant la formation, les news vont être remplacées pour une timeline twitter que vous trouverez dans Divers.");
define("_NEWS15_DATE", "10/11/2017");

define("_NEWS14_TITLE","Ajout de contenu (v1.2.2)");
define("_NEWS14_DESC", "Modification d'un script (Reber), ajout d'une nouveauté et ajout d'une formation");
define("_NEWS14_DATE", "01/11/2017");

define("_NEWS13_TITLE","Ajout de contenu (v1.2.1)");
define("_NEWS13_DESC", "Ajout de news, de divers contenus et un script");
define("_NEWS13_DATE", "28/11/2017");

define("_NEWS12_TITLE","Multiples changement (v1.2.0)");
define("_NEWS12_DESC", "<li>5 news</li><li>1 script</li><li>1 nouvelle page de points divers</li><li>refonte de la structure du site</li>");
define("_NEWS12_DATE", "22/10/2017");

define("_NEWS11_TITLE","Ajout de news (v1.1.8)");
define("_NEWS11_DESC", "Ajout de 4 news");
define("_NEWS11_DATE", "12/10/2017");

define("_NEWS10_TITLE","Ajout de news (v1.1.7)");
define("_NEWS10_DESC", "Ajout de 4 news");
define("_NEWS10_DATE", "01/10/2017");

define("_NEWS9_TITLE","Ajout de contenu (v1.1.6)");
define("_NEWS9_DESC", "Ajout d'un script sur la detection de fraud sur des carte de crédits, mise à jour de mon CV, ajout d'un livre ainsi que d'une chaine Youtube");
define("_NEWS9_DATE", "19/09/2017");

define("_NEWS8_TITLE","Ajout d'un script (v1.1.5)");
define("_NEWS8_DESC", "Ajout d'un script sur la mise en place d'un model de prix de loyer");
define("_NEWS8_DATE", "10/09/2017");

define("_NEWS7_TITLE","Ajout d'un script (v1.1.4)");
define("_NEWS7_DESC", "Ajout d'un script sur l'exploration de Réseaux de Neuronnes");
define("_NEWS7_DATE", "23/08/2017");

define("_NEWS6_TITLE","Ajout de contenu (v1.1.3)");
define("_NEWS6_DESC", "Ajout de plusieurs scripts et d'une News. Correction d'un bug d'encodage sur la fonction mail.");
define("_NEWS6_DATE","19/08/2017");

define("_NEWS5_TITLE","Ajout de contenu (v1.1.2)");
define("_NEWS5_DESC", "Ajout d'un site dans la section \"Apprendre Python\". Ajout de plusieurs scripts");
define("_NEWS5_DATE","16/08/2017");

define("_NEWS4_TITLE","Modification d'UI et Réglages Apache (v1.1.1)");
define("_NEWS4_DESC", "Amélioration de l'UI et correction de problèmes avec le cache");
define("_NEWS4_DATE","14/08/2017");

define("_NEWS3_TITLE","Modification d'UI et ajout du Multilangues (v1.1.0)");
define("_NEWS3_DESC", "Modification de la structure du site pour un support Français et Anglais <br/> Changement de l'interface");
define("_NEWS3_DATE","13/08/2017");

define("_NEWS2_TITLE","Resolutions de bug et Améliorations (v1.0.1)");
define("_NEWS2_DESC", "Correction de bugs et amélioration du code pour un chargement plus rapide");
define("_NEWS2_DATE","09/08/2017");

define("_NEWS1_TITLE","Mise en ligne (v1.0)");
define("_NEWS1_DESC", "Première mise en ligne de <a href=\"#\">nicolasmine.com</a>");
define("_NEWS1_DATE","08/08/2017");

?>