<?php
// fichier de langues en anglais

// Homepage
define("_WELCOME","Welcome on <a href=\"#\" class=\"white\">nicolasmine.com</a>");

define("_MENU1_TITLE","Scripts");
define("_MENU2_TITLE","Who am I ?");
define("_MENU3_TITLE","Learn Python");
define("_MENU4_TITLE","News");
define("_MENU5_TITLE","Misc");

define("_MENU1_DESC","In this section, I will share with you some scripts I made on Jupyter Notebook with explainations. Unortunately, it won't present Codingame puzzles as most of inputs are provided every turns and depends on our previous output. You can nevertheless refer to my <a href=\"https://github.com/Coni63\" target=\"_blank\">Github</a> but not presented on Notebook");
define("_MENU2_DESC","Wants to know more about myself, take a look to my Resume");
define("_MENU3_DESC","In this section, I will make you discover some contents (websites, youtube channel, books) I found usefull to learn Python or Programming in general.");
define("_MENU4_DESC","On this section, I will share with you some articles on various information or news");
define("_MENU5_DESC","This section will be a repository of miscelleanous information (websites, twitter account). Be curious !");

// Section CV
define("_SECTION_1", "About me");
define("_SECTION_2", "Formations");
define("_SECTION_3", "Professionnal Experiences and Interships");
define("_SECTION_4", "Skills");
define("_SECTION_5", "References");
define("_SECTION_6", "Contact");
define("_SECTION_7", "Social Networks");
define("_SECTION_8", "Hobbies");

define("_SUB1", "Data Scientist");
define("_SUB2", "Mechanical Engineer");

define("_SWITCH1", "Show Internships");
define("_SWITCH2", "Show Projects");

define("_SECTION_1_DESC", "Being interested by programming, I learned by myself some languages (Python, Javascript, VBA, PHP, SQL, R, Java). Since early 2017, I'm passionated with Machine-Learning. I validated in winter 2017/2018 a Master in Data Science on OpenclassRooms and started to learn R on DataCamp. I'm now working as Digitization Specialist where I'll have to use my different knowledge to automate several tasks (defect detection, quality predictions, ...)");

define("_FORM1_TITLE", "Mechanical Engineer - IFMA");
define("_FORM1_SUB", "Pole Machines, Mechanisms and Systems ");
define("_FORM1_LOC", "Clermont-Ferrand (France, 63)");
define("_FORM1_DATE", "2010 - 2013");
define("_FORM1_URL", "IFMA's website");

define("_FORM2_TITLE", "Higher School Preparatory Classes");
define("_FORM2_SUB", "Section Physics, Chemistry and Enginnering Sciences ");
define("_FORM2_LOC", "Auxerre (France, 89) in 1<sup>st</sup> year and Troyes (France, 10) in 2<sup>nd</sup>year");
define("_FORM2_DATE", "2008 - 2010");
define("_FORM2_URL", "Website of the 1<sup>st</sup> year @ Auxerre");
define("_FORM2_URL2", "Website of the 2<sup>nd</sup> year @ Troyes");

define("_FORM3_TITLE", "General Certificate of Education Advanced Levels");
define("_FORM3_SUB", "Option Enginnering Sciences - with Distinction");
define("_FORM3_LOC", "Sens (89)");
define("_FORM3_DATE", "2008");

define("_FORM4_TITLE", "Master Of Data Sciences");
define("_FORM4_LOC", "Online Classes (OpenClassrooms & CentralSupelec)");
define("_FORM4_DATE", "2017 - 2018");
define("_FORM4_URL", "OpenClassrooms");
define("_FORM4_INFO", "Training Ongoing");

define("_FORM5_TITLE", "Learning of langage R");
define("_FORM5_LOC", "E-learning (DataCamp)");
define("_FORM5_DATE", "2018 - XXXX");
define("_FORM5_URL", "DataCamp");
define("_FORM5_INFO", "Training Ongoing");

define("_EXP1_TITLE", "Industrial Designer");
define("_EXP1_DESC", "Design of PET injection Molds (for plastic bottles preforms). Creation of simple tools to simplify some tasks in VBA, Support of project's coordination");
define("_EXP1_DATE", "11/2014 - 12/2018");
define("_EXP1_URL", "Official Website");

define("_EXP2_TITLE", "Industrial project of end of studies - Designing a curved chain");
define("_EXP2_DESC", "During this project, I have to research an alternative to the current low-efficient system to cut branches on a tree. One of the alternatives was to design a curved chainsaw. This is the one I worked on. At the end of the project, a mechanical and thermal analysis has been done and a prototype was started");
define("_EXP2_DATE", "April - September 2013");
define("_EXP2_INFO", "3<sup>rd</sup> year Internship");
define("_EXP2_URL", "Official Website");

define("_EXP3_TITLE", "Propulsive efficiency optimization of a multi-rotor drone");
define("_EXP3_DESC", "The objective of this project was to review all influents parameters on the propulsion chain to improve flight time of drones, propose alternatives and do an experimental validation to estimate the gain in stationnary flight. A test bench and a protocol has been written and some theorical studies have been made based on APC's propellers");
define("_EXP3_DATE", "2012 - 2013 (120 h)");
define("_EXP3_INFO", "3<sup>rd</sup> year Projects");

define("_EXP4_TITLE", "Development and qualification of materials");
define("_EXP4_DESC", "In this intership, I participated to the logistics and tests for the development and validation of equipments to perform a reparation in an highly radioactive area. To simplify gestion of material, I've set-up an Access Database for equipment management and documentation then extended to other projects");
define("_EXP4_DATE", "May - September 2012");
define("_EXP4_INFO", "2<sup>nd</sup> year Internship");
define("_EXP4_URL", "Official Website");

define("_EXP5_TITLE", "Automatic marking machine for wood");
define("_EXP5_DESC", "During this project, the objective was the design of a complete autonomous machine for marking wood planks (Norm NIMP15). Solutions have been estimated, a complete design and sizing has been done for a machine marking with hot iron. Pricing has also been calculated to estimate the amortization for the company");
define("_EXP5_DATE", "2011 - 2012 (90h)");
define("_EXP5_INFO", "2<sup>nd</sup> year Projects");

define("_EXP6_TITLE", "Thinkmotion Project – Design of a closing door system");
define("_EXP6_DESC", "The objective was to design a 3D animated model for Thinkmotion European Project For this project I design a closing door system using cams");
define("_EXP6_DATE", "September 2011");
define("_EXP6_INFO", "2<sup>nd</sup> year Projects");

define("_EXP7_TITLE", "Digitization Specialist");
define("_EXP7_DESC", "As part of the Digitization team, the objective is to automate some stages of the mold production (test and inspection). To do so, the automation of some steps is necessary. This will allow to gather data and use them to create predictive models.");
define("_EXP7_DATE", "01/2019 - Today");
define("_EXP7_INFO", "Current Job");
define("_EXP7_URL", "Official Website");

define("_REF1_DESC", "I learnt as big part of Python on <a href=\"https://www.codingame.com/home\">Codingame</a>. This website propse different puzzle to solve by coding your own IA. There is sometimes some multiplayer tournaments. I participate actively on 4 of them :");
define("_REF1_URL", "See my profile");

define("_REF2_DESC", "Based on my current learning of Machine Learning, I decided to create a small website mixing WegGL technology with Machine Learning. The idea was to propose a new way to do a movie recommander. Instead of having movies listed, I wanted to represent them in a 3D space. The closer they are, the more similar they are. There is currently 5 version but the simpliest one remains the V4.");

define("_REF2_URL", "Link to website");
define("_REF2_URL_2", "Link to the repository");

define("_REF3_DESC", "This second website was a proposal made to simplify an administrative task we have to do in our daily work. The idea was to fill a form, this is afterward stored on the website and easy to search into afterward. Some content are removed for confidentiality reasons");
define("_REF3_URL", "Link to website");


define("_HOBBIE1", "VTT");
define("_HOBBIE2", "CODING");
define("_HOBBIE3", "MODEL AIR CRAFTING");

define("_NAME", "Name");
define("_NAME_PH", "John Doe");
define("_EMAIL", "Email");
define("_EMAIL_PH", "john.doe@example.com");
define("_MESSAGE", "Your message");
define("_MESSAGE_PH", "Your Message ...");
define("_SEND", "Send");
define("_COPY", "A copy of your message will be send to your email. <br/> HTML tags are not allowed");

define("_MODAL_PYTHON", "I learnt Python by myself mostly on <a href=\"https://www.codingame.com/home\">Codingame</a>. During my free time, I sometimes try to help other coders on Stack Overflow and OpenClassRoom. This allows me to discover sometimes other way to write something or discover other subjects.<br/>
                <div class=\"row\">
                  <div class=\"col-md-6\">
                      <t><b>Good knowledge</b></t><br/>
				      <ul>
				          <li>Std Libs (math, os, string, itertools, queue, datetime, pickle, threading, heapq)</li>
				          <li>Algorithmic 
                              <ul>
                                <li>Algorithmic Complexity</li>
                                <li>Graph theory</li>
                                <li>Pathfinding (A*, BFS, DFS, Djikstra)</li>
                                <li>Exploration (MiniMax, A/B pruning)</li>
                              </ul>
				          </li>
                          <li>Scientific libs (Numpy, Scipy, Scikit_learn, mathplotlib)</li>
                          <li>Supervised Machine Learning (Linear/Log regression, SVM, random forest, DNN)</li>
                          <li>Unsupervised Machine Learning (Manifolds/Clustering)</li>
                          <li>Neural Networks (Tensorflow / Keras)</li>
                          <li>Genetic Algorithms</li>
				      </ul>
                  </div>
                  <div class=\"col-md-6\">
                      <t><b>Basic knowledge</b></t><br/>
                      <ul>
                          <li>Django (MVC structure, auth module, BDD) and Flask</li>
                          <li>PyQt4 / PyQt5</li>
                          <li>Webscrapping with beautifulSoup</li>
                          <li>Reinforced Learning (Q-learning / DQN & variations like DDDQN with PER / PPO / PG)</li> 
                      </ul>
                  </div>
                </div>
                You can find some of my scripts on <a href=\"https://github.com/Coni63/scripts_Python\">Github</a>");

define("_MODAL_JS", "<span class=\"tab\">I discovered Javascript while creating a Greasemonkey script for an online game. The goal of this script was initially to improve some UI elements but it goes further to number notation, automatic sending of forms, adding some missign features or informations up to a bot for the market. At the end the script was around 3500 lines.</span><br/>
                <span class=\"tab\">During creation of website I also discovered JQuery.</span><br/><br/> 
                All those projects makes me having a good knowledge in:
                <ul>
                  <li>HTML parsing</li>
                  <li>Adding events or objects</li>
                  <li>Validation of fields with regex</li>
                  <li>Handling POST/GET requests</li>
                </ul>");

define("_MODAL_PHP", "After writing 3 websites in PHP including this one (You will find the 2 others in the next part), I have good bases on :
                <ul>
                    <li>Structure</li>
                    <li>Database managmenet (on MySQL)</li>
                    <li>Creating basic functions</li>
                    <li>Handling errors</li>
                </ul>
                Nevertheless, there is still some points I'm not a master:
                <ul>
                    <li>Handling sessions and access</li>
                    <li>The MVC Structure</li>
                    <li>the use of Framewoks (Laravel, Symfony, ...)</li>
                    <li>The POO</li>
                </ul>");

define("_MODAL_HTML", "By having nearly always started websites from scratches, I have a correct knowledge in HTML. Nevertheless I have gaps in CSS. That's why I prefer to use library like Bootstrap to get a website more \"uniform\" and adaptive. I would consider my level as strong enought to design a small website/application but not for a \"fancy\" design.");

define("_MODAL_VBA", "With the programming logic I acquired and the experience I have in VBA, I can be autonomous to write some VBA code. Nevertheless, this is not a language I particularly like. I've made some macros on Outlook to filter email and fill some info in an Excel, Excel to automatically generate a particluar layout with datas or in Access to multiple small tasks");
                
define("_MODAL_OFFICE", "I have a pretty good level in Office Pack including Access. I made a database in Access during my 2<sup>nd</sup> year internship and support a teammate while doing one at work. During my intership, my goalk was to handle :
<ul>
    <li>material's managment (robots, consoles, cameras, ...)</li>
    <li>cable's managment (based on connectic and use)</li>
    <li>camera's managment</li>
    <li>listing material for each intervention</li>
    <li>Storing and access to documentation</li>
</ul>
More generally, my knowledge in Office package is :");

define("_MODAL_Java", "I started to learn Java by doing few projects. I wanted to understand the logic completely Oriented Object and being able to do some things with it if required (mainly for performances purposes). I have now some basics about code structuration (maven, packages) and structures (HashSet, Vectors, ...). I mainly used it with Processing to have a simple 2D rendered (to replace pygame for example).");

define("_MODAL_R", "In complement of Python, I started to learn R on <a href=\"https://www.datacamp.com/profile/nicolasmine\" target=\"_blank\">DataCamp</a>. I wanted to learn it to be at least able to make some specific visualisations unavailable in Python. So I learned the basics and the elements needed for data processing / visualization. I did not learn what is needed for modeling.");

define("_MODAL_SQL", "For multiple projects, I had to manipulate SQL. I won't say that I'm fully efficient but I have anought knowledge to be able to query what I need from databases if I know the structure.");

define("_CLOSE_MODAL", "Close");

?>