<?php
// fichier de langues en francais
 
// Homepage
define("_WELCOME","Bienvenue sur <a href=\"#\" class=\"white\">nicolasmine.com</a>");

define("_MENU1_TITLE","Scripts");
define("_MENU2_TITLE","Qui suis-je ?");
define("_MENU3_TITLE","Apprendre Python");
define("_MENU4_TITLE","News");
define("_MENU5_TITLE","Divers");

define("_MENU1_DESC","Dans cette section, je vous partagerai des scripts que j'ai faits sur Jupyter Notebook avec des explications. Cependant, je ne présenterais pas les puzzles de Codingame car les entrées dépendent souvent de la sortie précédente que l'on donne. Vous pouvez néanmoins vous référez à mon <a href=\"https://github.com/Coni63\" target=\"_blank\">Github</a> mais les scripts ne sont ni commentés ni sur Notebooks");
define("_MENU2_DESC","Envie d'en savoir plus sur moi, jetez un coup d'oeil à mon CV");
define("_MENU3_DESC","Dans cette section, je vous présenterai différents contenus que j'ai découvert en apprenant Python ou la programmation en générale.");
define("_MENU4_DESC","Dans cette section, je partagerai diverses articles sur des informations ou nouveautés.");
define("_MENU5_DESC","Dans cette section, je partagerai des informations diverses (sites web, compte twitter, etc...). Soyez curieux !");

// Section CV
define("_SECTION_1", "A propos de moi");
define("_SECTION_2", "Formations");
define("_SECTION_3", "Experiences Professionnelles et Stages");
define("_SECTION_4", "Compétences");
define("_SECTION_5", "Références");
define("_SECTION_6", "Contact");
define("_SECTION_7", "Réseaux Sociaux");
define("_SECTION_8", "Passions");

define("_SUB1", "Data Scientist");
define("_SUB2", "Ingénieur Mécanique");

define("_SWITCH1", "Voir les Stages");
define("_SWITCH2", "Voir les projets");

define("_SECTION_1_DESC", "Je suis actuellement designer industriel dans une société produisant des moules d'injection plastique. Etant très intéressé par la programmation, j'apprends de façon autodidacte plusieurs langages (du Python au VBA en passant par le PHP, Javascript, SQL) depuis quelques années et plus récemment (env. 1an) j'ai decouvert le Machine-Learning. Afin de valider mes acquis avec un vrai diplôme, je suis actuellement un Master en ligne sur la plateforme OpenClassrooms. Ayant fini le cours, le mois dernier, j'ai entrepris d'apprendre aussi le language statistique R très utilisé dans l'analyse de données.");

define("_FORM5_TITLE", "Apprentissage du language R");
define("_FORM5_LOC", "Cours en Ligne (DataCamp)");
define("_FORM5_DATE", "2018 - XXXX");
define("_FORM5_URL", "DataCamp");
define("_FORM5_INFO", "Formation en cours");

define("_FORM4_TITLE", "Master en Data Sciences");
define("_FORM4_LOC", "Cours en Ligne (OpenClassrooms & CentralSupelec)");
define("_FORM4_DATE", "2017 - 2018");
define("_FORM4_URL", "OpenClassrooms");
define("_FORM4_INFO", "Formation en cours");

define("_FORM1_TITLE", "Ingénieur Mécanique - IFMA");
define("_FORM1_SUB", "Pôle Machines, Mécanismes et Systèmes ");
define("_FORM1_LOC", "Clermont-Ferrand (63)");
define("_FORM1_DATE", "2010 - 2013");
define("_FORM1_URL", "Site de l'IFMA");

define("_FORM2_TITLE", "Classes Préparatoires aux Grandes Ecoles (CPGE)");
define("_FORM2_SUB", "Filières PCSI et PSI");
define("_FORM2_LOC", "Auxerre (89) en 1<sup>ère</sup> année et Troyes (10) en 2<sup>ème</sup>année");
define("_FORM2_DATE", "2008 - 2010");
define("_FORM2_URL", "Site de l'école à Auxerre");
define("_FORM2_URL2", "Site de l'école à Troyes");

define("_FORM3_TITLE", "Baccalaurét Scientifique - Option Sciences de l'Ingénieur");
define("_FORM3_SUB", "Mention Assez Bien");
define("_FORM3_LOC", "Sens (89)");
define("_FORM3_DATE", "2008");

define("_EXP1_TITLE", "Designer Industriel");
define("_EXP1_DESC", "Conception de moules d'injection plastique (pour des préformes de bouteilles). Mise en place de petits outils en VBA et aide à la coordination de projets");
define("_EXP1_DATE", "11/2014 - Aujourd'hui");
define("_EXP1_INFO", "Poste Actuel");
define("_EXP1_URL", "Site Officiel");

define("_EXP2_TITLE", "Stage de fin d'études - Conception d'une scie à chaine courbe");
define("_EXP2_DESC", "Lors de ce stage, j'ai dû rechercher une alternative pour améliorer le système peu performant d'ébranchage sur les têtes d'abattage forestières. Une des alternatives proposées était de concevoir une tronçonneuse courbe avec un guide chaine incurvé. C'est sur ce sujet que j'ai travaillé. Lors de ce projet une étude théorique (thermique, dynamique et RDM) à été mise en place et un prototype a été démarré.");
define("_EXP2_DATE", "Avril - Septembre 2013");
define("_EXP2_INFO", "Stage de 3<sup>ème</sup> année");
define("_EXP2_URL", "Site Officiel");

define("_EXP3_TITLE", "Optimisation du rendement propulsif d'un drone multirotor");
define("_EXP3_DESC", "L'objectif de ce projet était de rechercher des paramètres influent dans la chaîne de propulsion sur la durée de vol des drones, proposer des alternatives et valider expérimentalement du gain d’autonomie possible d’un drone en vol stationnaire. Un banc d'essai a été conçu, une étude faite sur des hélices de marque APC ainsi qu'un protocole expérimental.");
define("_EXP3_DATE", "2012 - 2013 (120 h)");
define("_EXP3_INFO", "Projet de de 3<sup>ème</sup> année");

define("_EXP4_TITLE", "Stage Assistant Ingénieur - Développement et qualification de matériels");
define("_EXP4_DESC", "Durant ce stage, j'ai participé à la préparation d'une réparation de goulotte dans l'usine de retraitement de la Hague. En plus de l'assistance lors des essais sur maquette, j'ai mis en place une base de donnée sur Access pour gérer la logistique et de remplacer la gestion sur Excel en place à l'origine.");
define("_EXP4_DATE", "Mai - Septembre 2012");
define("_EXP4_INFO", "Stage de 2<sup>ème</sup> année");
define("_EXP4_URL", "Site Officiel");

define("_EXP5_TITLE", "Machine automatisée de marquage de bois");
define("_EXP5_DESC", "Lors de ce projet, l'objectif était de produire un banc de marquage de planches pour l'export (Norme NIMP 15). Une recherche de solutions a été faite ainsi qu'une conception et un dimensionnement complet pour une machine de marquage au fer chaud. Un devis a aussi été estimé pour calculer l'amortissement pour la société");
define("_EXP5_DATE", "2011 - 2012 (90h)");
define("_EXP5_INFO", "Projet de de 2<sup>ème</sup> année");

define("_EXP6_TITLE", "Projets Thinkmotion – Réalisation d’un système de fermeture de porte");
define("_EXP6_DESC", "L'objectif du projet Européen Thinkmotion est de faire une librairie de modèles 3D animées de brevets existants. Pour ce projet, j'ai choisi un système de fermeture de porte avec une came");
define("_EXP6_DATE", "Septembre 2011");
define("_EXP6_INFO", "Projet de de 2<sup>ème</sup> année");

define("_REF1_DESC", "J'ai appris en majorité le langage Python sur <a href=\"https://www.codingame.com/home\">Codingame</a>. Ce site propose différents puzzles a résoudre en programmant un algorithme. Ce site propose parfois aussi des tournois d’IA sur une semaine où l'on affronte d'autres codeurs. 
                        Parmi les tournois proposés, j'ai particulièrement pris part à 4 d'entre eux :");
define("_REF1_URL", "Voir mon profil");

define("_REF2_DESC", "Suite à ma formation en Data Science, j'ai decidé de créer un petit site mixant la technologie WebGL et le machine Learning. L'idée était de proposer un recommandeur de films différent. Au lieu d'avoir une liste de film similaires, Je voulais les représenter dans un espace 3D. Le plus proches 2 films sont, le plus similaires ils sont.");

define("_REF2_URL", "Voir le site");
define("_REF2_URL_2", "Voir le repository");

define("_REF3_DESC", "Ce site a été une proposition faite pour simplifier certaines tâches administratives. Ce site sauvegarde le formulaire avec le numéro de projet et un numéro de changement en clé. Ceci permettait donc ensuite d'accéder plus facilement au changement fait. Certaines parties ont été enlevées sur cette version pour des raisons de confidentialité. ");
define("_REF3_URL", "Voir le site");


define("_HOBBIE1", "VTT");
define("_HOBBIE2", "CODING");
define("_HOBBIE3", "AEROMODELISME");

define("_NAME", "Nom");
define("_NAME_PH", "Alain Dupont");
define("_EMAIL", "Email");
define("_EMAIL_PH", "alain.dupont@example.com");
define("_MESSAGE", "Votre Message");
define("_MESSAGE_PH", "Votre Message ...");
define("_SEND", "Envoyer");
define("_COPY", "Une copie vous sera envoyé sur votre adresse mail. <br/> Les balises HTML ne sont pas autorisées");

define("_MODAL_PYTHON", "J'ai appris le python de manière autodidacte en majorité en résolvant des puzzles sur <a href=\"https://www.codingame.com/home\">Codingame</a>. Lors de mon temps libre j'aide aussi sur Stack Overflow et OpenClassRoom d'autres codeurs. Cela permet au passage de voir d'autres problèmes.<br/>
                <div class=\"row\">
                  <div class=\"col-md-6\">
                      <t><b>Bonne connaissances</b></t><br/>
				      <ul>
				          <li>Librairies standards (math, os, string, itertools, queue, datetime, pickle)</li>
				          <li>Algorithmiques 
                              <ul>
                                <li>Complexité algorithmique</li>
                                <li>Algorithme de graphes</li>
                                <li>Pathfinding (A*, BFS, DFS, Djikstra)</li>
                              </ul>
				          </li>
                          <li>Librairies Scientifique (Numpy, Scipy, Scikit_learn, mathplotlib)</li>
                          <li>Machine-Learning supervisé (Linear/logistic regression, SVM, Random Forest, DNN)</li>
				      </ul>
                  </div>
                  <div class=\"col-md-6\">
                      <t><b>Connaissances de bases</b></t><br/>
                      <ul>
                          <li>Librairies standards (threading, heapq)</li>
                          <li>Django (modèle MVC, auth module, BDD) et Flask</li>
                          <li>PyQt4</li>
                          <li>Webscrapping with beautifulSoup</li>
                          <li>Tensorflow
                            <ul>
                            <li>Convolutionnal Neural Network</li> 
                            <li>Recurrent Neural Network</li> 
                            <li>Reinforced Learning</li> 
                            </ul>
                          </li>
                          <li>Machine-Learning non supervisé (Clustering)</li>
                          <li>Algorithmes génétiques</li>
                      </ul>
                  </div>
                </div> <!-- End of rows -->
                Une bonne part de mes algorithmes sont disponible sur mon <a href=\"https://github.com/Coni63/scripts_Python\">Github</a>");

define("_MODAL_JS", "<span class=\"tab\">J'ai appris le javascript surtout lors de la création d'un script pour un site de jeu en ligne. Ce script comprenait différentes fonction allant du changement de notation des chiffres à l'automatisation d'envoi de formulaire en passant par des ajouts de features (ajout d'informations manquantes, simulation de résultats, calcul d'optimums). Ce script faisait environ 3500 lignes à son maximum.</span><br/>
                <span class=\"tab\">Differents sites m'ont permis d'apprendre la syntaxe de JQuery.</span><br/><br/> 
                Ces differents projets m\'ont permis notament d'avoir de bonnes connaissances en :
                <ul>
                  <li>Navigation dans une page HTML</li>
                  <li>Ajout d'objets/events</li>
                  <li>Controle des champ d'un formulaire</li>
                  <li>Creation de requete POST/GET</li>
                </ul>");

define("_MODAL_PHP", "Ayant fait 3 sites en PHP (vous trouverez les 2 précédents dans la section suivantes) dont celui-ci, j'ai de bonnes bases sur :
                <ul>
                    <li>La structuration</li>
                    <li>La connexion a une BDD (dans mon cas MySQL uniquement)</li>
                    <li>La creation de fonctions de bases</li>
                    <li>La gestion des erreurs lors d'une requête</li>
                </ul>
                Cependant j'admet avoir des lacunes sur certains points comme:
                <ul>
                    <li>La gestion des sessions et des droits particuliers</li>
                    <li>La conception sur une structure MVC</li>
                    <li>L'utilisation de frameworks (Laravel, Symfony, ...)</li>
                    <li>La POO</li>
                </ul>");

define("_MODAL_HTML", "Ayant toujours écrit les sites du départ, j'ai une assez bonne aisance en HTML. Cependant je ne suis pas particulièrement à l'aise avec le CSS. Pour avoir un site \"uniforme\", j'ai plus tendance à m'orienter vers Bootstrap que de faire le css par moi-même.
                Mes connaissances devraient suffire pour coder une application mais plus difficilement pour un site au \"design\" très original.");

define("_MODAL_VBA", " Ayant écrit quelques programmes en VBA (pour de la mise en page, un peu de calcul), j'ai des connaissances en VBA me permettant de faire ce dont j'ai besoin. Cependant n'ayant pas un attrait particulier pour ce langage, je n'ai jamais fait de gros projets dans ce langage.
                J'ai eu à utiliser VBA majoritairement sur Excel, un peu sur Access et une fois sur Outlook (filtrage de mail et envoi d'information sur une Excel)
");
                
define("_MODAL_OFFICE", "J'ai de bonne connaissance sur le pack Office incluant Access. J'ai notamment utilisé Access pour faire une BDD de gestion de projet lors de mon stage de 2eme année. Celui-ci permettait notamment :
<ul>
    <li>la gestion du materiel (robots, cables, consoles, cameras, ...)</li>
    <li>la gestion et le partage de cables (selon les connectiques et l'usage)</li>
    <li>la gestion des caméra pour chaque robots</li>
    <li>la gestion du materiel necessaire pour chaque intervention</li>
    <li>la gestion de la documentation</li>
</ul>
Plus globalement mon niveau sur Office est :");

define("_CLOSE_MODAL", "Fermer");

?>