<?php
// fichier de langues en anglais

// Homepage
define("_WELCOME","Welcome on <a href=\"#\" class=\"white\">nicolasmine.com</a>");

define("_MENU1_TITLE","Scripts");
define("_MENU2_TITLE","Who am I ?");
define("_MENU3_TITLE","Learn Python");
define("_MENU4_TITLE","News");
define("_MENU5_TITLE","Misc");

define("_MENU1_DESC","In this section, I will share with you some scripts I made on Jupyter Notebook with explainations. Unortunately, it won't present Codingame puzzles as most of inputs are provided every turns and depends on our previous output. You can nevertheless refer to my <a href=\"https://github.com/Coni63\" target=\"_blank\">Github</a> but not presented on Notebook");
define("_MENU2_DESC","Wants to know more about myself, take a look to my Resume");
define("_MENU3_DESC","In this section, I will make you discover some contents (websites, youtube channel, books) I found usefull to learn Python or Programming in general.");
define("_MENU4_DESC","On this section, I will share with you some articles on various information or news");
define("_MENU5_DESC","This section will be a repository of miscelleanous information (websites, twitter account). Be curious !");

// NEWS

define("_SECTION_UP", "Top");
define("_SECTION_DOWN", "Bottom");

define("_TITLE_NEWS", _MENU4_TITLE);
define("_HEADER_NEWS", _MENU4_DESC);
define("_SHOW_DIVERS", "Voir la Source");

define("_DIVERS1_TITLE", "Python : 1<sup>st</sup> Language according IEEE Spectrum");
define("_DIVERS1_SOURCE", "http://spectrum.ieee.org");
define("_DIVERS1_DATE", "2017-07-18");
define("_DIVERS1_CONTENT", "After some years on the top 10 Programming Languages, Python stand on the winner's platform. Ranked among 48 languages and 12 metrics, it is only few points ahead C and Java... To be continued");

define("_DIVERS2_TITLE", "Should you use tabs or spaces for identation ??");
define("_DIVERS2_SOURCE", "Stack Overflow");
define("_DIVERS2_DATE", "2017-06-15");
define("_DIVERS2_CONTENT", "Did you already ask yourself if tabs is better than spaces? Based on a survey made on Stack Overflow, developers who use spaces earn more money than the one which used tabs... Not sure this is serious, isn't it ? :)");

define("_DIVERS3_TITLE", "An AI beats top players on DOTA 2");
define("_DIVERS3_SOURCE", "Open AI");
define("_DIVERS3_DATE", "2017-08-16");
define("_DIVERS3_CONTENT", "On 7-11 august 2017, a special tournament took place, top players on DOTA 2 played against an IA on 1vs1 mode (created by OPEN AI). The result is impressive, the AI lost only 2 matches over 28 ! ");

define("_DIVERS4_TITLE", "IBM predicts an increase by 28% for \"Data Scientist\" by 2020");
define("_DIVERS4_SOURCE", "Forbes");
define("_DIVERS4_DATE", "2017-05-13");
define("_DIVERS4_CONTENT", "Based on a study made by IBM, \"Data Scientist/Analyst\" demand will increase by 28% withing 3 years (around 364,000 new jobs). 59% will be in Financial, Insurances, IT and Professional Services sectors");

define("_DIVERS5_TITLE", "Visual Search in Bing");
define("_DIVERS5_SOURCE", "Bing Blog");
define("_DIVERS5_DATE", "2017-09-19");
define("_DIVERS5_CONTENT", "A new feature arrives in BING - you can now search similar items based on a picture. How they did it? A faster CNN based on a new architecture");

define("_DIVERS6_TITLE", "Turn a Selfie into 3D, it's now possible");
define("_DIVERS6_SOURCE", "Nvidia Developer");
define("_DIVERS6_DATE", "2017-09-19");
define("_DIVERS6_CONTENT", "The University of Nottingham and Kingston succeed to transform a 2D selfie to 3D model. How? Deep Learning of course with a CNN");

define("_DIVERS7_TITLE", "NVidia make machine Learning faster with TensorRT v3");
define("_DIVERS7_SOURCE", "Nvidia Developer");
define("_DIVERS7_DATE", "2017");
define("_DIVERS7_CONTENT", "In the race to best Deep Learning system, computing time is a key. After the design of the TPU by Google last year (<a href=\"https://www.forbes.com/sites/moorinsights/2017/05/22/google-cloud-tpu-strategic-implications-for-google-nvidia-and-the-machine-learning-industry/#490910a23af7\" target=\"_blank\">TensorFlow Process Unit)</a> (coté matériel), NVidia just released a new \"driver\" allowing a increase of speed by around 40 on new Volta's GPU.");

define("_DIVERS8_TITLE", "Quasi Recurrent Neural Network implemented on PyTorch");
define("_DIVERS8_SOURCE", "Github");
define("_DIVERS8_DATE", "2017-09-29");
define("_DIVERS8_CONTENT", "During the last few years, Recurrent Neural Network evolved a lot to speed up training or improve accuracy. From a RNN to GRU (Gate Recurrent Unit)  then LSTM (Long Short Term Memory), a new model just arrived on PyTorch, it's QRNN. With performances between 1.3x and 16x faster than a CudNN's LSTM, we probably will heard a lot about this new model !");

define("_DIVERS9_TITLE", "TensorFlow add a new estimator \"monolitic\" to ease generalization");
define("_DIVERS9_SOURCE", "Blog Google");
define("_DIVERS9_DATE", "2017-10-11");
define("_DIVERS9_CONTENT", "In some cases, model generalizes poorly due to noises in the dataset. In order to ease generalizations on some cases, TensorFlow implemented an estimator which is molotic to avoid overfitting. Let's see..");

define("_DIVERS10_TITLE", "TensorFlow 1.4.0 is out !");
define("_DIVERS10_SOURCE", "Twitter @TensorFlow");
define("_DIVERS10_DATE", "2017-10-11");
define("_DIVERS10_CONTENT", "The latest version of TensorFlow is now out. You can find the changelog <a href=\"https://github.com/tensorflow/tensorflow/releases/tag/v1.4.0-rc0\" target=\"_blank\">here</a>");

define("_DIVERS11_TITLE", "AI succeed to learn to fight without coded behaviors");
define("_DIVERS11_SOURCE", "OpenAI Blog");
define("_DIVERS11_DATE", "2017-10-11");
define("_DIVERS11_CONTENT", "After the success of OpenAI versus best player on DOTA2, The team created a competition where AI  only have an objective and no actions. They have to determine by themselves a way to win and create their own behavior. This is different to \"gym\" where we have a list of action and the only objective is to choose the best one.");

define("_DIVERS12_TITLE", " WPA2 security protocol has been KRACKed");
define("_DIVERS12_SOURCE", "mashable");
define("_DIVERS12_DATE", "2017-10-16");
define("_DIVERS12_CONTENT", "The widespread security protocol for wireless communication has been cracked. The protocol WPA is widely used by WiFi but also some other wireless communication. The vulnerability is not on encryption process so a fix will be deployed by providers");

define("_DIVERS13_TITLE", "AI learn to cooperate");
define("_DIVERS13_SOURCE", "OpenAI Blog");
define("_DIVERS13_DATE", "2017-06-08");
define("_DIVERS13_CONTENT", "OpenAI developped an algorithm able to make AI cooperates. Called Multi Agent Deep Deterministic Policy Gradient (MADDPG), this new algorithm opens incredible possibilities !");

define("_DIVERS14_TITLE", "AlphaGo evolves to become AlphaGo Zero");
define("_DIVERS14_SOURCE", "Thenextweb & Deepmind");
define("_DIVERS14_DATE", "2017-10-18");
define("_DIVERS14_CONTENT", "AlphaGo, the first IA beating the best world player of GO, is now replaced by AlphaGo Zero. Instead of learning based on recorded human games, this new one learn from scratch. The result is impressive. In 3 days, this new IA beats AlphaGo. In 40 days, it reached a super-human level (while using 44 times less computation power)");

define("_DIVERS15_TITLE", "ML algorithms simulates fluid in real time");
define("_DIVERS15_SOURCE", "physicsforests");
define("_DIVERS15_DATE", "2017");
define("_DIVERS15_CONTENT", "A company just set up a fluid engine based on Machine Learning. The interest ? a Real time rendering and faster");

define("_DIVERS16_TITLE", "What can Artificial Intelligence do for your business ?");
define("_DIVERS16_SOURCE", "ZDnet");
define("_DIVERS16_DATE", "2017-10-19");
define("_DIVERS16_CONTENT", "Recently Machine Learning has the wind in its sails. You can therefore ask yourself about the interest of this new technology in your company. Where can it be used? What is his interest? How to do ? ZDnet answer you!");

define("_DIVERS17_TITLE", "Facebook and Intel Are Joining Forces for Artificial Intelligence");
define("_DIVERS17_SOURCE", "futurism.com");
define("_DIVERS17_DATE", "2017-10-23");
define("_DIVERS17_CONTENT", "Since the era of AI, hardware's run is at its peak. According the Wall Street Journal, Facebook and Intel are working together to develop a new processor for ML called <b>Intel Nervana</b>");

define("_DIVERS18_TITLE", "Intel is going to release a framework for Reinforced Learning");
define("_DIVERS18_SOURCE", "intelnervana.com");
define("_DIVERS18_DATE", "2017-10-20");
define("_DIVERS18_CONTENT", "Intel has recently started to work on ML. Alongside their new processor called <b>Intel Nervana</b>, Intel is going to release a new framework to learn Reinforced Learning. It will be a good tool to link with gym to learn this field without frustration due to complexe processes");

define("_DIVERS19_TITLE", "Visual search tools arrives on Ebay");
define("_DIVERS19_SOURCE", "techcrunch");
define("_DIVERS19_DATE", "2017-10-27");
define("_DIVERS19_CONTENT", "A month after the announce from BING regarding a visual search tool on their search engine, Ebay is doing the same and is going to propose a tool to look at object based on a picture");

define("_DIVERS20_TITLE", "Artificial Intelligence Beats CAPTCHA");
define("_DIVERS20_SOURCE", "http://spectrum.ieee.org");
define("_DIVERS20_DATE", "2017-10-26");
define("_DIVERS20_CONTENT", "Captchas are widely used to avoid robots to perform some taks. This has just been beat by AI. By copying eyes's vision, a new algorithm is able to solve captchas with an unprecedented accuracy !");

define("_DIVERS21_TITLE", "Synthetic Gradients can replace standard Gradient Descent");
define("_DIVERS21_SOURCE", "Github and Youtube");
define("_DIVERS21_DATE", "2017-10-24");
define("_DIVERS21_CONTENT", "With deeper and deeper Neural Network, the backpropagation is slower and slower. To speed up the training, a new concept just arrives \"The Synthetic Gradients\". It allows the gradient calcul on every layer in parallel and make a training faster... We are now waiting for implementation on most commons Libraries");

?>