<?php
// fichier de langues en francais
 
// Homepage
define("_WELCOME","Bienvenue sur <a href=\"#\" class=\"white\">nicolasmine.com</a>");

define("_MENU1_TITLE","Scripts");
define("_MENU2_TITLE","Qui suis-je ?");
define("_MENU3_TITLE","Apprendre Python");
define("_MENU4_TITLE","News");
define("_MENU5_TITLE","Divers");

define("_MENU1_DESC","Dans cette section, je vous partagerai des scripts que j'ai faits sur Jupyter Notebook avec des explications. Cependant, je ne présenterais pas les puzzles de Codingame car les entrées dépendent souvent de la sortie précédente que l'on donne. Vous pouvez néanmoins vous référez à mon <a href=\"https://github.com/Coni63\" target=\"_blank\">Github</a> mais les scripts ne sont ni commentés ni sur Notebooks");
define("_MENU2_DESC","Envie d'en savoir plus sur moi, jetez un coup d'oeil à mon CV");
define("_MENU3_DESC","Dans cette section, je vous présenterai différents contenus que j'ai découvert en apprenant Python ou la programmation en générale.");
define("_MENU4_DESC","Dans cette section, je partagerai diverses articles sur des informations ou nouveautés.");
define("_MENU5_DESC","Dans cette section, je partagerai des informations diverses (sites web, compte twitter, etc...). Soyez curieux !");

// NEWS

define("_SECTION_UP", "Haut de page");
define("_SECTION_DOWN", "Bas de page");

define("_TITLE_NEWS", _MENU4_TITLE);
define("_HEADER_NEWS", _MENU4_DESC);
define("_SHOW_DIVERS", "Voir la Source");

define("_DIVERS1_TITLE", "Python : 1<sup>er</sup> Language selon IEEE Spectrum");
define("_DIVERS1_SOURCE", "http://spectrum.ieee.org");
define("_DIVERS1_DATE", "18/07/2017");
define("_DIVERS1_CONTENT", "Apres quelques années dans le top 10 des meilleurs langages, Python atteint cette année la 1ère marche du podium. Classé parmi 48 langages et 12 points d'évaluation, il devance C et Java de seulement quelques points ... A suivre");

define("_DIVERS2_TITLE", "Devriez-vous utiliser les tabulation ou les espaces pour indenter ?");
define("_DIVERS2_SOURCE", "Stack Overflow");
define("_DIVERS2_DATE", "15/06/2017");
define("_DIVERS2_CONTENT", "Vous êtes-vous déjà posé la question si les tabs sont meilleurs que les espaces? D'après un sondage fait sur Stack overflow, les developpeurs qui utilisent les espaces sont mieux payés que ceux utilisant les tabulations... Pas sûr que ce soit sérieux, n'est-ce pas? :)");

define("_DIVERS3_TITLE", "Une IA bat les meilleurs joueurs mondiaux sur DOTA 2");
define("_DIVERS3_SOURCE", "Open AI");
define("_DIVERS3_DATE", "16/08/2017");
define("_DIVERS3_CONTENT", "Du 7 au 11 août 2017, un tournoi un peu particulier a eu lieu, les meilleurs joueurs mondiaux de DOTA 2 ont affronté une IA en 1vs1 (crée par OPEN AI). Le résultat est bluffant, l'IA n'a perdu que 2 matchs sur 28 ! ");

define("_DIVERS4_TITLE", "IBM prédit une augmentation de la demande de \"Data Scientist\" de 28% d'ici 2020");
define("_DIVERS4_SOURCE", "Forbes");
define("_DIVERS4_DATE", "13/05/2017");
define("_DIVERS4_CONTENT", "D'après une étude d'IBM, la demande en \"Data Scientist/Analyst\" va augmenter de 28% d'ici 3 ans (soit environ 364 000 nouveaux postes) dont 59% pour les secteurs de la Finance, Assurances, IT et Services aux Professionnels");

define("_DIVERS5_TITLE", "Recherche Visuel sur BING");
define("_DIVERS5_SOURCE", "Bing Blog");
define("_DIVERS5_DATE", "19/09/2017");
define("_DIVERS5_CONTENT", "Une nouveauté vient d'apparaitre sur BING - la recherche d'objets similaires basé sur une photo. Comment-ont-ils réussi? Un CNN beaucoup plus rapide avec une architecture différente (travaillant par régions)");

define("_DIVERS6_TITLE", "Passer un Selfie en une image 3D, c'est maintenant possible !");
define("_DIVERS6_SOURCE", "Nvidia Developer");
define("_DIVERS6_DATE", "19/09/2017");
define("_DIVERS6_CONTENT", "L'université de Nottingham et Kingston ont réussi le tour de force de générer des rendus 3D de faces avec 1 seule photo. Comment? Biensur le Deep Learning avec un CNN");

define("_DIVERS7_TITLE", "NVidia accelère encore le Deep Learning avec TensorRT v3");
define("_DIVERS7_SOURCE", "Nvidia Developer");
define("_DIVERS7_DATE", "2017");
define("_DIVERS7_CONTENT", "Dans la course au Deep Learning, le temps de calcul est un point crucial. Après la conception du TPU par Google l'an dernier (<a href=\"https://www.forbes.com/sites/moorinsights/2017/05/22/google-cloud-tpu-strategic-implications-for-google-nvidia-and-the-machine-learning-industry/#490910a23af7\" target=\"_blank\">TensorFlow Process Unit)</a> (coté matériel), NVidia vient de sortir un nouveau \"driver\" permettant une acceleration des calcul x40 sur les GPU Volta.");

define("_DIVERS8_TITLE", "Quasi Recurrent Neural Network implémentés sur PyTorch");
define("_DIVERS8_SOURCE", "Github");
define("_DIVERS8_DATE", "29/09/2017");
define("_DIVERS8_CONTENT", "Dans les dernières années les Recurrent Neural Network ont bien évolué afin d'être entrainé plus vite et de manière plus précise. Par un passage du RNN au GRU (Gate Recurrent Unit) puis au LSTM (Long Short Term Memory), un nouveau modèle plus rapide vient dêtre intégré à PyTorch. Avec des performances entre 1.3x et 16x plus rapide qu'un LSTM avec CudNN, on risque d'entendre parler de ce modèle dans les mois à venir !");

define("_DIVERS9_TITLE", "TensorFlow implémente un estimateur monotone pour faciliter la généralisation des modèles");
define("_DIVERS9_SOURCE", "Blog Google");
define("_DIVERS9_DATE", "11/10/2017");
define("_DIVERS9_CONTENT", "Dans certains cas, des modèles ne se généralisent pas correctement car des points du dataset ont trop de bruit. Pour faciliter la généralisation dans certain cas, TensorFlow vient d'implémenter un estimateur monotone permettant de mieux coller dans certaines circonstances. A suivre...");

define("_DIVERS10_TITLE", "TensorFlow 1.4.0 est sorti !");
define("_DIVERS10_SOURCE", "Twitter @TensorFlow");
define("_DIVERS10_DATE", "11/10/2017");
define("_DIVERS10_CONTENT", "La version 1.4 de TensorFlow vient d'être publié. Trouvez toutes les nouveautés <a href=\"https://github.com/tensorflow/tensorflow/releases/tag/v1.4.0-rc0\" target=\"_blank\">ici</a>");

define("_DIVERS11_TITLE", "Des IA apprennent à s'affronter sans avoir de comportements codés");
define("_DIVERS11_SOURCE", "OpenAI Blog");
define("_DIVERS11_DATE", "11/10/2017");
define("_DIVERS11_CONTENT", "Après la reussite de OpenAI face au meilleurs joueurs de DOTA2, l'équipe a mis en place des compétition avec juste un objectif fourni à l'IA. Celle-ce devrait par elle même trouver comment le faire et quand. Cela change par rapport à \"gym\" car dans celui-ci, la liste des actions est fournie.");

define("_DIVERS12_TITLE", "Le protocol de sécurité WPA2 a été cracké");
define("_DIVERS12_SOURCE", "mashable");
define("_DIVERS12_DATE", "16/10/2017");
define("_DIVERS12_CONTENT", "Le protocol le plus utilisé pour encrypter des communications vient d'être cracké. Celui-ci concerne le protocol WPA2 utilisé très largement par le WIFI mais aussi d'autres communication sans fil. La faille n'étant pas sur l'encryption, celle-ci devrait être corrigée.");

define("_DIVERS13_TITLE", "Des IA apprennent à coopérer");
define("_DIVERS13_SOURCE", "OpenAI Blog");
define("_DIVERS13_DATE", "08/06/2017");
define("_DIVERS13_CONTENT", "OpenAI a développé cet été un algorithme capable de faire coopérer les IA entre elles. Appelé Multi Agent Deep Deterministic Policy Gradient (MADDPG), ce nouvel algorithme ouvre encore des possibilités énormes !");

define("_DIVERS14_TITLE", "AlphaGo evolue et devient AlphaGo Zero");
define("_DIVERS14_SOURCE", "Thenextweb & Deepmind");
define("_DIVERS14_DATE", "18/10/2017");
define("_DIVERS14_CONTENT", "AlphaGo qui a été la 1ère IA a battre le meilleur joueur mondial de GO est remplacé par AlphaGo Zero. A la place de l'apprentissage en visionnant des milliers de match, celle ci apprend de zéro sans aucune bases. Le résultat est impressionnant. En 3j, cette IA est deja meilleur que AlphaGo. En 40j, elle atteint un niveau sur-humain (en utilisant 44 fois moins de puissance de calcul)");

define("_DIVERS15_TITLE", "Des Algorithmes de ML simulent des fluides en temps réel");
define("_DIVERS15_SOURCE", "physicsforests");
define("_DIVERS15_DATE", "2017");
define("_DIVERS15_CONTENT", "Une société a mis en place un moteur physique pour les fluides basés sur du ML. L'interêt ? Un rendu en temps réel et allégé en calcul");

define("_DIVERS16_TITLE", "A quoi peut bien servir l'Intelligence Artificielle dans votre entreprise ?");
define("_DIVERS16_SOURCE", "ZDnet");
define("_DIVERS16_DATE", "19/10/2017");
define("_DIVERS16_CONTENT", "Depuis peu, le Machine Learning a le vent en poupe. On peut donc se poser la question de l'intérêt de cette nouvelle technologie dans son entreprise. Ou peut-elle être utilisée ? Quel est son interêt ? Comment faire ? ZDnet vous réponds !");

define("_DIVERS17_TITLE", "Facebook et Intel s'associent pour la recherche sur les IA");
define("_DIVERS17_SOURCE", "futurism.com");
define("_DIVERS17_DATE", "23/10/2017");
define("_DIVERS17_CONTENT", "Depuis l'avènement de l'IA, la course aux meilleurs Hardwares est a son apogée. D'après le Wall Street Journal, Facebook et Intel s'associeraient pour le developpement d'un nouveau processeur appelé <b>Intel Nervana</b>");

define("_DIVERS18_TITLE", "Intel va sortir un framework pour le Reinforced Learning");
define("_DIVERS18_SOURCE", "intelnervana.com");
define("_DIVERS18_DATE", "20/10/2017");
define("_DIVERS18_CONTENT", "Intel se lance depuis peu dans le ML. En parallèle de leur nouveau processeur appelé <b>Intel Nervana</b>, Intel va aussi sortir un framework pour l'apprentissange du reinforced Learning. Un bon outils a coupler avec Gym pour apprendre sans la frutration pour toutes personne commencant cette partie du ML très complexe.");

define("_DIVERS19_TITLE", "La recherche visuelle arrive sur Ebay");
define("_DIVERS19_SOURCE", "techcrunch");
define("_DIVERS19_DATE", "27/10/2017");
define("_DIVERS19_CONTENT", "A peine un mois apres l'annonce de Bing d'intégrer un moteur visuelle sur leur moteur de recherche, Ebay fait de même et va sortir un outil pour rechercher les objets basées sur une photo");

define("_DIVERS20_TITLE", "Une IA est capable de resoudre les Captchas");
define("_DIVERS20_SOURCE", "http://spectrum.ieee.org");
define("_DIVERS20_DATE", "26/10/2017");
define("_DIVERS20_CONTENT", "Les captchas utilisées pour éviter des robots de faire certaines tâche vient d'être mis à l'épreuve. En effet, en copiant le système de perception de l'oeil, un tout nouveau algorithme est capable de résoudre les captchas avec un taux de réussite jamais atteint !");

define("_DIVERS21_TITLE", "Synthetic Gradients pourrait remplacer la Descente de Gradient actuel");
define("_DIVERS21_SOURCE", "Github et Youtube");
define("_DIVERS21_DATE", "24/10/2017");
define("_DIVERS21_CONTENT", "Avec la mise en place de NN de plus en plus profond, la backpropagation devient de plus en plus lente. Pour accelerer cette tache, un nouveau concept vient d'être crée \"Le Gradient Synthetique\". Celui-ci permet le calcul du gradient sur chaque layer en parrallele et permet donc d'accelerer le temps d'entrainement... On attend just l'implémentation sur les librairies classiques.");

?>