<?php
// fichier de langues en anglais

// Homepage
define("_WELCOME","Welcome on <a href=\"#\" class=\"white\">nicolasmine.com</a>");

define("_MENU1_TITLE","Scripts");
define("_MENU2_TITLE","Who am I ?");
define("_MENU3_TITLE","Learn Python");
define("_MENU4_TITLE","News");
define("_MENU5_TITLE","Misc");

define("_MENU1_DESC","In this section, I will share with you some scripts I made on Jupyter Notebook with explainations. Unortunately, it won't present Codingame puzzles as most of inputs are provided every turns and depends on our previous output. You can nevertheless refer to my <a href=\"https://github.com/Coni63\" target=\"_blank\">Github</a> but not presented on Notebook");
define("_MENU2_DESC","Wants to know more about myself, take a look to my Resume");
define("_MENU3_DESC","In this section, I will make you discover some contents (websites, youtube channel, books) I found usefull to learn Python, Data Sciences, A.I. or Programming in general.");
define("_MENU4_DESC","On this section, I will share with you some articles on various information or news");
define("_MENU5_DESC","This section will be a repository of miscelleanous information (websites, twitter account). Be curious !");


// Learn Python
define("_TITLE_LP", "LEARN PYTHON");
define("_HEADER_LP", _MENU3_DESC);

define("_LINALG", "Linear Algebra");
define("_NUM_AN", "Numerical Analysis");
define("_ALGO", "Algorithmic");
define("_VULGARISATION", "Vulgarization");
define("_MULTI_SUB", "Multi Subjects");
define("_TALK", "Live Talk");
define("_AI", "Artificial Intelligence");
define("_RL", "Reinforcement Learning");

define("_SECTION_BOOK", "Books");
define("_SECTION_YOUTUBE", "Youtube Channels");
define("_SECTION_SITE", "Websites");

define("_BOOK1_DESC", "This book is the first one I read after knowing basics of Python. It makes me stepped up because it goes through 128 various algorithms and keep an eye on Algorithmic Complexity. As a consequence, it's not written for complete beginner because some codes are quite complicated to understand. 
Among the topics, we can find subjects from work on strings to pathfinding through geometry.");

define("_BOOK2_DESC", "This book is the second one I went through. It's starting with a presentation of <b>Numpy</b>'s library then to the use <b>Scipy</b> in connection with <b>Numpy</b>. This book presents severals functions to solve problems of <i>Linear Algebra</i> to <i>Machine Learning</i> through <i>Numerical Analysis</i> and <i>Signal Processing</i>. Being more oriented on the library presentation, I didn't read completely the book. It is especially a nice tool to keep on hand in case of problems.");

define("_BOOK3_DESC", "This book is the must have if you want to learn <i>Machine Learning</i>. In part 1, you will get an explaination of how to handle a problem of either <i>Regression</i> or <i>Classification</i> before to presents you all models more in details, how to optimize them and how to reduce dimensions. In part 2, you gonna discover <i>Neural Networks</i> and <i>Deep Learning</i> based on the well-knows library <b>Tensorflow</b>. This book is really complete, without going too deep into calculation.<br/>BONUS : all example have their own Jupyter Notebook with additionnal content to go further");

define("_BOOK4_DESC", "After reading the book presented above, you will probably be disappointed by this one as it look very empty. However there is more content regarding some points (word embedding, Recurrent Neural Network). Also the author presents some basic knowledge about tensorflow which are interesting. If you want an advice, buy/read this book prior reading \"Hands on Machine Learning with Scikit-Learn and TensorFlow\"");

define("_BOOK5_DESC", "Impressive book regarding AI from A to Z. Withing the thousand of pages, you will go in detail in all fields of AI (from simple tree search to Reinforcement Learning). Pay attention that there is no codes provided in the book in any languages but they propose script online to test it on exercices. I'm currently reading the book and will probably takes a lot of times :) ");

define("_BOOK6_DESC", "Compare to the book above, this one focus only on Reinforcement Learning. You will learn several way to built you AI by using this \"new\" field of science. I didn't started it yet, I'll keep you posted !");

define("_BOOK7_DESC", "The more I do projects, the more I realize that I need a deeper understanding of How and Why Neural Network works to be able to set more complicated structure than simple NN, RNN or CNN. This book only take into consideration the Neural Network Science. Except the fact that it is not 100% up-to-date (written in 2016), it's a really good source of knowledge about NN. There is also no codes but only pseudo-code to understand some functions.");

define("_YT1_DESC", "Want to code in a good spirit ? On this channel, you gonna see some coding challenges and how to solve it with either Javascript with the library P5.js or Java usign Processing. Every problems are solved with clear explainations and an algorithm including a graphical representation to ease the understanding.");

define("_YT2_DESC", "You want to code a website in Python, knows more about ML and finances, write a game on pygame? This channel is definitely made for you ! You gonna find several playlists for every subject with a project made on them. One drawback, some videos are \"old\" and may be not 100% up-to-date (e.g. Django)");

define("_YT3_DESC", "This channel goes more in details on NN functionning and how to set them up. It's the must-have for every persons interested in this new field of study. <br/> +1 for the dynamism !");

define("_YT4_DESC", "First step in ML or lost in-between all kind of NN ? This channel provides short animations to have an overview how ML is working. No prerequisites needed, it's just an overview of all this science");

define("_YT5_DESC", "A huge Library of sujects, from AngularJS to Linux through big data, you gonna find lot of contents interesting. One drawback, the sound quality is poor and speaker is sometime a bit difficult to understand.");

define("_YT6_DESC", "On this channel, you gonna find a group of shows about latest progress of every programming languages. It's similar to TEDx but for programming");

define("_YT7_DESC", "This Channel is the channel of Google Devs. You will find on it several contents including some nice presentation regarding TensorFlow or other Google's features.");

define("_SITE1_DESC", "You know a programming language and wants to challenge yourself on new problems ? This site is for you! Sove several problems by coding your own IA, fight other coders in multiplayer clashes or in a 7-day tournaments, choici is yours.<br/> This website supports 27 languages, let's code !");

define("_SITE2_DESC", "I discovered this website not a long time ago and not tried it for now. Like Codingame but for ML, it offers differents datasets to train on ML. You build your own model, you evaluate your model on a specific dataset and you get your accuracy and ranking. If you want to improve your knowledge on ML, this is the place to be !");

define("_SITE3_DESC", "Should I really present this forum? If you don't know it, it's coding's WikiPedia. You have a question? Someone probably already replied about it on this website :)");

define("_SITE4_DESC", "This website has been built by Codingame's team. The objective is to propose courses made by Developpers for Developpers. The website remains a beta but has already plenty of good content");
?>