<?php
// fichier de langues en anglais

// Homepage
define("_WELCOME","Welcome on <a href=\"#\" class=\"white\">nicolasmine.com</a>");

define("_MENU1_TITLE","Scripts");
define("_MENU2_TITLE","Who am I ?");
define("_MENU3_TITLE","Learn Python");
define("_MENU4_TITLE","News");
define("_MENU5_TITLE","Misc");

define("_MENU1_DESC","In this section, I will share with you some scripts I made on Jupyter Notebook with explainations. Unortunately, it won't present Codingame puzzles as most of inputs are provided every turns and depends on our previous output. You can nevertheless refer to my <a href=\"https://github.com/Coni63\" target=\"_blank\">Github</a> but not presented on Notebook");
define("_MENU2_DESC","Wants to know more about myself, take a look to my Resume");
define("_MENU3_DESC","In this section, I will make you discover some contents (websites, youtube channel, books) I found usefull to learn Python or Programming in general.");
define("_MENU4_DESC","On this section, I will share with you some articles on various information or news");
define("_MENU5_DESC","This section will be a repository of miscelleanous information (websites, twitter account). Be curious !");

define("_SECTION_UP", "Top");
define("_SECTION_DOWN", "Bottom");

// Scripts
define("_SHOW_PUZZLE", "See the puzzle");
define("_SHOW_SOLUTION", "See the solution");
define("_DL_SOLUTION", "Download Notebook");
define("_SHOW_REPO", "See Repository");
define("_SHOW_VID", "Watch video");
define("_DL_JAR", "Downlaod jar file");
define("_DL_SCRIPT", "Download the script");

define("_SECTION_EASY", "Easy Puzzles");
define("_SECTION_MEDIUM", "Medium Puzzles");
define("_SECTION_HARD", "Hard Puzzles");
define("_SECTION_V_HARD", "Very Hard Puzzles");
define("_SECTION_COMMUNITY", "Community Puzzles");
define("_SECTION_OTHER", "Others");

define("_TITLE_CG", _MENU1_TITLE);
define("_HEADER_CG", _MENU1_DESC);

define("_PUZZLE1_TITLE", "Chuck Norris encoding");
define("_PUZZLE1_DESC", "In this puzzle, the objective is to encode a sentence to a \"unary\" encrypted sentence.");

define("_PUZZLE2_TITLE", "Closest Defibrillator");
define("_PUZZLE2_DESC", "In this puzzle, the objective is to return the closest Defibrillator to a given position knowing all defibrillator's positions");

define("_PUZZLE3_TITLE", "Cellular Automaton");
define("_PUZZLE3_DESC", "In this notebook, we gonna create a Cellular Automaton with a visible GUI made on PyQT. It's similar to the Game of Life but using another pattern system");

define("_PUZZLE4_TITLE", "Convex Hull");
define("_PUZZLE4_DESC", "In this exercice, we gonna go thru an algorithm to determine the convex Hull to a set of X-Y points");

define("_PUZZLE5_TITLE", "Pathfinding - Dijkstra Algorithm");
define("_PUZZLE5_DESC", "In this exercice, we gonna explore the well know pathfinding algorithm called Dijkstra");

define("_PUZZLE6_TITLE", "Perceptron");
define("_PUZZLE6_DESC", "The exercice on this notebook is to create a train the elementary element of a Neural Network called Perceptron");

define("_PUZZLE7_TITLE", "Travelling Salesman Problem");
define("_PUZZLE7_DESC", "In this workbook, the objective is to create a Genetic Algorithm to find a good solution to the well known NP-Hard problem called Travelling Salesman Problem");

define("_PUZZLE8_TITLE", "Tridiagonal Random Matrice");
define("_PUZZLE8_DESC", "This workbook has been created to help someone in OpenClassRoom's forum. The idea is to observe the change on Eigenvectors linked to noises in a Tridiagonal Matrix");

define("_PUZZLE9_TITLE", "ML - Regression - Auto MPG Dataset");
define("_PUZZLE9_DESC", "The objective in this workbook is to create a model of car's consumption based on some datas. Datas are available <a href=\"https://archive.ics.uci.edu/ml/datasets/auto+mpg\" target=\"_blank\">here</a>");

define("_PUZZLE10_TITLE", "ML - Classification - Iris Dataset");
define("_PUZZLE10_DESC", "In this workbook, we are going to explore the well known Iris dataset and fit a Forest Tree classifier to visualize how it works");

define("_PUZZLE11_TITLE", "ML - Tensorflow - Logistic Classification - Moons Dataset");
define("_PUZZLE11_DESC", "In this exercice, the objective is to create a (linear and polynomial) Logistic Classifier on Moons dataset using Tensorflow");

define("_PUZZLE12_TITLE", "ML - Tensorflow - Exploration of Neural Network");
define("_PUZZLE12_DESC", "In this workbook, the objective is to see the impact of some parameters of a Neural Network or Features on the training time/speed");

define("_PUZZLE13_TITLE", "ML - Scikit Learn - House rent prices");
define("_PUZZLE13_DESC", "This workbook set up a model to determine the rent based on the surface and district. This exercice is based on an exercice from OpenClassRoom");

define("_PUZZLE14_TITLE", "ML - Scikit Learn - Kaggle - Credit Card Fraud");
define("_PUZZLE14_DESC", "In this workbook, we will explore a very unbalanced dataset about credit card fraud found on <a href=\"https://www.kaggle.com/dalpozz/creditcardfraud\" target=\"_blank\">Kaggle</a>. On this dataset, we will discover the advantage to perform the PCA on an <b>undersampling</b> dataset to simplify the model.");

define("_PUZZLE15_TITLE", "ML - Scikit Learn / Keras - Kaggle - Human Resources Analytics");
define("_PUZZLE15_DESC", "In this workbook, we will explore a dataset regarding reasons to leave a company found on  <a href=\"https://www.kaggle.com/ludobenistant/hr-analytics\" target=\"_blank\">Kaggle</a>.");

define("_PUZZLE16_TITLE", "ML - Keras - Introduction to RNNs with Reber's grammar");
define("_PUZZLE16_DESC", "This workbook introduces Recurrent Neural Network highly used for \"temporals\"'datas. In this introduction we will test some model based on reber's grammar.");

define("_PUZZLE17_TITLE", "ML - FBProphet - Predict delay of flights");
define("_PUZZLE17_DESC", "During the Master of Data Sciences, we had to predict lateness of flight based on date/hour/company/airports/... During this one, I tried multiple models but in this notebook we will discover the librairy called FBProphet used to find pattern in timeseries.");

define("_PUZZLE18_TITLE", "ML - Scikit Learn - Test of UMAP on clustering of articles");
define("_PUZZLE18_DESC", "UMAP is a new Algorithm of dimension's reduction found on <a href=\"https://arxiv.org/abs/1802.03426\">Arxiv</a>. To try it, an improvement has been tried on the clustering of articles from the Project 5 of the Master of Data Science. All articles will be converted to a TF-IDF matrix. Then the Latent Semantic Analysis will be performed on this matrix to have a dense result and a Kmeans will be applied. For the visualisation, the TSNE will be compared with the UMAP.");

define("_PUZZLE19_TITLE", "ML - Keras - Simulation of double pendulum using RNNs");
define("_PUZZLE19_DESC", "After creating a simulator of the double pendulum, a dataset will be created in order to try to train a RNN on it. By using few LSTM, a correct simlution of this chaotic system has been reached.");

define("_PUZZLE20_TITLE", "ML - Keras - Simulation of double pendulum using RNNs (part 2)");
define("_PUZZLE20_DESC", "Previously, we tried to simulate a double pendulum using RNN. To do so, we used fixed model parameters (length and mass). In this workbook we will try to extend this model to simulate a model with also variable parameters and wider initial parameters");

define("_PUZZLE21_TITLE", "ML - Keras - Classification Dataset QuickDraw with 20 similar classes");
define("_PUZZLE21_DESC", "In this notebook, differents CNNs will be tested on a dataset of images more complex than MNIST still made by hand (20 classes, animals only, 28x28 in B&W). Classic CNNs will be tested as well as the CapsNet before looking more in detail at the bad classifications. We will see that these are often errors related to the designer...");

define("_PUZZLE22_TITLE", "ML - Numpy - Test of Neuro-Evolution instead of Reinforcement Learning");
define("_PUZZLE22_DESC", "In this notebook, I tried to train a Neural Network to solve the CartPole problem of gym library using Genetic Algorithm isntead of Reinforcement Learning with Back Propagation. After Analysis of the behavior, a linear Model has been trained to perform nearly as well as NN");

define("_PUZZLE23_TITLE", "DA - R - Exploration of Codingame Leaderboard");
define("_PUZZLE23_DESC", "Being learning R, I used a webscrapped version of the leaderboard of Codingame website in order to apply multiple learning done during classes (working on a dataset, ploting with ggplot and reporting with R markdown). In this Notebook, we will explore the leaderborad and the balance of player. In addition, we will try to find trick to climb fast in the ranking.");

define("_PUZZLE24_TITLE", "ML - Tensorflow - DeepDream video");
define("_PUZZLE24_DESC", "Based on a playlist from Sentdex, his code has been reused and slightly modified in order to generate a DeepDream video using \"inception\"'s model. There is no Notebbok for this project but a README is availabel on Github quite complete.");

define("_PUZZLE25_TITLE", "ML - Keras - Audio Classification");
define("_PUZZLE25_DESC", "As we can do with MNIST, this Notebbok explore audio file in an unsupervised way then try to perform a classification on it (with simple ANNs, CNNs and RNNs) ");

define("_PUZZLE26_TITLE", "ML - Keras - Audio Classification FMA");
define("_PUZZLE26_DESC", "This week, we will explore another more complete audio dataset which is FMA dataset. As I did previously, I'll try to create a classifier of music type. We will discover that the success on the previous model was only due to overfitting and this doesn't work as good as expected in addition of having other drawbacks.");

define("_PUZZLE27_TITLE", "ML - Keras - Audio Segmentation FMA");
define("_PUZZLE27_DESC", "After testing the audio classification based on pattern recognition on the FFT signal, a new approach was tested using segmentation and clustering . This method exploits the data similarly as text data and has the advantage of being compatible with any length of audio sample.");

define("_PUZZLE28_TITLE", "ML - Keras - Audio Classification FMA using meta data");
define("_PUZZLE28_DESC", "After testing the audio classification based on pattern recognition on the FFT signal and the audio clustering, I wanted to try classification using meta data extracted from audio. The part 1 is a try a the small balanced dataset with only 1 genre per song and the second one is a try on the full unbalanced multilabel dataset but without good results.");

define("_PUZZLE29_TITLE", "ML - Kaggle Comp. - Free Sound Audio Tagging");
define("_PUZZLE29_DESC", "To finish with the audio processing, I decided to work on another dataset from a Kaggle Competition to classify audio too. Compare to FMA dataset, this one is slightly unbalanced in term of class but also very different in term of duration. To do the classification, we will extract the same features as FMA and add the duration before to classify it. The result is not perfect but reach still 74% of accuracy.");

define("_PUZZLE30_TITLE", "ML - Numpy + Scipy - Regression on circular datas");
define("_PUZZLE30_DESC", "At work I faced a question on how to find the best circle fitting a set of point measured in (X, Y) coordinate. This gaves me the idea to take a deeper look at this question and find algorithms (mainly using Scipy), test them and implement them in a syntax close to sklearn library");

define("_PUZZLE31_TITLE", "ML - NoSLQ + sklearn + nltk - Sentiments Analysis on Tweets");
define("_PUZZLE31_DESC", "A new project I'm starting uses sentiments analysis on tweets. For now, I've uploaded a Notebook regarding the query of tweets and storage in a NoSQL database and a second one where I tried to set a simple model to predict sentiment of a tweet.");

define("_PUZZLE32_TITLE", "Data Analysis - Sentiments Analysis on Tweets");
define("_PUZZLE32_DESC", "On the previous script, we set-up an API to query tweets and do the sentiment analysis. This script ran during the match France vs Argentina and this notebook is a Data Analysis of the sentiment during the match");

define("_PUZZLE33_TITLE", "AI - Solver of Taquin");
define("_PUZZLE33_DESC", "Slightly different subject today. We will try to create a simple solver of Taquin using graphs algorithms. A BFS, DFS and A* will be created in order to find a solution to 3x3 Taquin (not 4x4 yet as it is highly more complex)");

define("_PUZZLE34_TITLE", "DA - Python - Exploration of Codingame Competition's LearderBoard");
define("_PUZZLE34_DESC", "After a discussion regarding programming languages, I wanted to take a look at most used programming language for IA in general. After extracting datas from Competition's LearderBoard, we will explore results and try to understand the choice.");

define("_PUZZLE35_TITLE", "IA - Java - Genetic algorithm and PID");
define("_PUZZLE35_DESC", "This week I made a project where I wanted to create in Java (using processing) as small genetic algorithme able to \"drive\" a solid between doors like with flappy bird. To have a fast learning, I provide a trajectory to follow and the genome is the parameters of the PID and the speed along x-axis. ");

define("_PUZZLE36_TITLE", "ML - Keras - Heartbeat Classification");
define("_PUZZLE36_DESC", "In this Notebook, the goal was to redo the model published in the paper <a href=\"https://arxiv.org/abs/1805.00794\">ArXviv 1805.00794</a>. We will also see that even if the result is very good, there is a very strong overfitting making the model impossible to reuse on others ECGs.");

define("_PUZZLE37_TITLE", "GA - Java - Code tester");
define("_PUZZLE37_DESC", "This small project is a comparator of 4 algorithms to find a code based only on the number of correct digits. The first one is trying digits one by one for each position to find the correct one. The second one is a genetic algorithm with the fitness based on number of correct digits. The third one is a greedy algorithm and the last one is a random generator.");

define("_PUZZLE38_TITLE", "Algorithm - Java - Fractal");
define("_PUZZLE38_DESC", "To continue with \"Processing\" in Java. I wanted to learn how to use a bit more the mouse. To do so, I create a fractal renderer. With a left-click, you can change the Complex Number used in the series. With right-click, you can span the image and with mouse wheel, you can zoom in/out.");

define("_PUZZLE39_TITLE", "Android + Java - Bluetooth communication");
define("_PUZZLE39_DESC", "For this second project, I wanted to learn a bit of Android. The idea was to be able to create a simple app which takes the values of sensors of the phone and send it to a script running in Java on my computer. At the beginning, I wanted to be able to create a small game contolled by sensors but there is too much noise. But at least I succeed to understand how an Android app is working and how to use the bluetooth (which was my main goal).");

define("_PUZZLE40_TITLE", "ML - FBProphet - Exploration of Air Quality in Madrid");
define("_PUZZLE40_DESC", "This week, I decided to reuse a new time the library FBProphet on another dataset with more data than the plane delay which was only on 1 year. This dataset is lighter but have 18years of records about the Airquality in Madrid (taken every hour in 24 points). This dataset is more suitable for Time Models like this model. In this we will discover the impact of human activity on pollution.");

define("_PUZZLE41_TITLE", "AI - Tensorflow / Gym - Presentation of the Q-Learning");
define("_PUZZLE41_DESC", "In this Notebook, we will explore the most simple algorithm to learn a policy. It's called Q-Learning. To do so, we will start with the simplest example which is the search of the shortest path in a graph. Then, we will use gym to try it with few puzzle having different challenges (sparse reward, large space-state, continuous input/output). This example will lead to future algorithms in the future.");

define("_PUZZLE42_TITLE", "ML - Keras/Sklearn/Gensim - Recipes classification");
define("_PUZZLE42_DESC", "This Notebook is an extension of the work done to participate to Kaggle's competition \"What's Cooking\". The objective is to classificy the origin of a recipe based on ingredients. In this one, multiple pre-processing will be tried and few models with corrects results.");

define("_PUZZLE43_TITLE", "IA - Keras/Gym - Introduction to Deep-Q Network");
define("_PUZZLE43_DESC", "In a previous script, we saw the restrictions that were reached with Q-Learning. Another approach proposed by DeepMind in 2013 was to give the task of evaluating the Q-value to a Neural Network. Deep-Q Network was born. In this notebook, we will see the principle and create our first DQN");

define("_PUZZLE44_TITLE", "Libs - Python - Presentation of 2 libs");
define("_PUZZLE44_DESC", "Being stuck in a futur project, I'm posting less and less projects. This week I wanted to share 2 libraries I found and wanted to try for a while. There is TPOT which uses Genetic Algorithms to optimise the pre-processing steps and Black which is a code formatter for python file.");

define("_PUZZLE45_TITLE", "Simulation - PyCUDA/Scipy - Comparison GPU vs CPU for Conway's Game of Life");
define("_PUZZLE45_DESC", "Following a discussion I got on a forum, I wanted to have a look at performances of GPU for non-matrix computation. I decided to do the trial on the Game of Life proposed by Conway. In this notebook, we will compare performances of 3 different approaches.");

define("_PUZZLE46_TITLE", "IA - Keras/Gym - Policy Gradient on Cartpole");
define("_PUZZLE46_DESC", "Another approach compared to Deep-Q Network, which predicts the expected futur reward of taking an action at a given state, is to predict directly the action. This is what is proposed with Policy Gradient model and we will discover it in this notebook.");

define("_PUZZLE47_TITLE", "IA - Keras/Gym - Proximal Policy Optimization on Cartpole");
define("_PUZZLE47_DESC", "For few years now, Policy Gradient became more or less obsolete. Another algorithm a bit more complex (but more performant) was published by OpenAI in 2017 which is the Proximal Policy Optimization. Due to it's simplicity, it also replaced in several cases the DeepQ Network. In this notebook, we will set-up this model on Cartpole again.");

define("_PUZZLE48_TITLE", "Simulation of Momentum Trading - Python - Data Preparation");
define("_PUZZLE48_DESC", "In Finance, an optimization technique of a Portfolio is the Momentum Trading. This method has been studied for a long time and shows performances above classics investments proposed by banks. In a series of Notebooks, the goal will be to make a simulator on past performances of ETFs and check if this is still true in 2018.");

define("_PUZZLE49_TITLE", "Simulation of Momentum Trading - Python - Simple Simulation");
define("_PUZZLE49_DESC", "Previously, we pre-processed the history of ETFs. This notebook will do a first simple model taking into consideration the performance to estimate the possible benefit of this method. The idea is to have a proof of concept.");

define("_PUZZLE50_TITLE", "Simulation of Momentum Trading - Python - Benchmark");
define("_PUZZLE50_DESC", "In the previous notebook, a simple model was made to check that this method is more or less working. The next step is to run simulations with multiple parameters to see \"how safe\" this method is");

define("_PUZZLE51_TITLE", "Simulation of Momentum Trading - Python - LSTM");
define("_PUZZLE51_DESC", "To try to improve/stabilize the decision about ETFs, we can try to train a Reccurent Neural Network with last N-weeks of data to predict the futur performance. This is what I tried to do on this last notebook.");

define("_PUZZLE52_TITLE", "Web-Scrapping - Python - Birthday Bot");
define("_PUZZLE52_DESC", "Following a video of Micode, I wanted to do a bot on twitter. For this project, celebrities's birthday dates were extracted from a website and a bot will be set up to wish on daily basis an happy birthday to celebrities on Twitter");

define("_PUZZLE53_TITLE", "ML - Python - Pose Estimation");
define("_PUZZLE53_DESC", "Compared to previous scripts, this one doesn't have any Notebooks as I only created a pipeline to process a video trhough a Pose Estimation Model called DensePose. This project has been done on the video clip called \"Skibidi\" as there is challenges for the model (more or less persones, costumes, fast moves, ...)");

define("_PUZZLE54_TITLE", "ML - Python - Bayesian Networks");
define("_PUZZLE54_DESC", "On a previous project, I discovered what are Bayesian Networks. To understand a bit more, I decided to do few exercices about that. In this Notebook, I dig a bit into \"pgmpy\" library with an example and an exercice. After that, I took the opportunity to do a word generator using Markov Model.");

define("_PUZZLE55_TITLE", "Simulation - Python - Multiple knapsack problem ");
define("_PUZZLE55_DESC", "Let's assume we want to assemble a stack of parts. How can we minimize the variation of a specific criteria along all the produced part ? This is what I wanted to look at in this Notebook isung Genetic Algorithms.");

define("_PUZZLE56_TITLE", "Reinforcement Learning - Python/Tensorflow - Minesweeper Bot");
define("_PUZZLE56_DESC", "After learning DQN and a bit of PPO, I wanted to apply it on a medium scale project. The minesweeper appeared good. Howerver I realized that it's not the case because the environment is partially observable and stochastic. As a result, I just trained 2 models : <br> -The first one should predict the probability of a bomb given the neighborhood (5x5 grid) <br>-The scond one in the full grid. <br>Unfortunately the result of the full grid is not very good and the other one is not very convenient...");

define("_PUZZLE57_TITLE", "Optimization - Python - Filters decomposition ");
define("_PUZZLE57_DESC", "In image processing, a common step is the application of convolutionnal filters. Based on the size of the filter, the time required to process an image can takes time. In this Notebook, we will see how this can be improved a lot by using filter decomposition");

define("_PUZZLE58_TITLE", "Optimization - Python - The Centrifuge Problem ");
define("_PUZZLE58_DESC", "In this last weeks, I made some Codingame puzzles and I found on youtube a nice problem I decided to solve. The solution is only a py file as there is not a lot to explain. The solution is presented on the attached video.");

define("_PUZZLE59_TITLE", "Optimization - Python - Sudoku Solver ");
define("_PUZZLE59_DESC", "I found on Kaggle a Dataset of 1 million Sudoku. I decided to download it to check if I could solve them but also check what makes them difficult to solve (for an algorithm). 3 algorithms will be compared. To finish, the top-4 most complex sudoku will be tested on these algos");

define("_PUZZLE60_TITLE", "NetworkX - Python - Facebook Network ");
define("_PUZZLE60_DESC", "Previously, I discovered <a href=\"https://www.youtube.com/watch?v=MySkCFFgiRQ\"> this video </a> by Michael Launay explaining a funny fact. In most of cases, you will have the impression of having less friends than them on Facebook. So I decided to use my previous learning on NetworkX to check this out.");

define("_PUZZLE61_TITLE", "Cryptography - Python - Quantum Toss Coin ");
define("_PUZZLE61_DESC", "On youtube, Physics Girl presented a way to play at distance the game of the Toss Coin. This is using light and quantum physics. This gave me the idea to start learning a bit cryptography and this is the first notebook of this subject.");

define("_PUZZLE62_TITLE", "Cryptography - Python - RSA ");
define("_PUZZLE62_DESC", "On the domain of Cryptography, one of the most common Asymmetrical Key Encryption is the RSA. In this Notebook, we will dig into this algorithm (how it works and a simple example)");

define("_PUZZLE63_TITLE", "Cryptography - Python - Elliptical Curve Cryptographie");
define("_PUZZLE63_DESC", "While starting tolearn Cryptography, I discovered the principle of Elliptical Curve Cryptography. This amazed me with the principle of being able to use the Fast exponentiation principle on geometries. In this Notebook, we will go thru the principle of Diffie-Hellman Key Exchange but also the implementation of ECC to generate keys.");

define("_PUZZLE64_TITLE", "Cryptography - Python - Block Cypher encryption");
define("_PUZZLE64_DESC", "Previously, we discovered how to create symmetrical and asymmetrical keys. This was used with very basic encryption methods afterward. In this notebook, we will explore how to make encryption on any kind of data. There is multiple solutions existing but we will only test the 2 safest modes (CBC and CTR) with the 2 safest symmetrical encryption algorithms (AES and Triple DES).");

define("_PUZZLE65_TITLE", "Cryptography - Python - Discrete Log Attack");
define("_PUZZLE65_DESC", "In the first Notebooks about Cryptography, we speak about the Key creation and says that they need to be very long. In this Notebook, we will see how to attack a Public Key to find the Private Key and being able to decrypt messages.");

define("_PUZZLE66_TITLE", "Image Preprocessing - Python - Seam Carving");
define("_PUZZLE66_DESC", "During a Codingame puzzle, I discovered the Seam Carving algorithm that could be a very good solution for pre-processing images in a machine learning project. It would help to resize images without stretching them as is the case in most cases");

define("_PUZZLE67_TITLE", "Image Classification - Keras - Class Activation Map");
define("_PUZZLE67_DESC", "During a previous competition Kaggle, I discovered the principle of Class Activation Map (CAM) to visualize which areas the model uses to make the prediction. After the discovery related to impact of texture on classification, I wanted to use this method on this image (and others) in one Notebook.");

define("_PUZZLE68_TITLE", "Image Classification - Keras - Seam Carving Preprocessing");
define("_PUZZLE68_DESC", "Previously we saw a technic used to resize image without losing area of interest and also visualize which part of an image is used to make the classification. In this Notebook, we will test to use Seam Carving on large images instead of classic resizing and see the impact on the classification.");

define("_PUZZLE69_TITLE", "Image Classification - Keras - Seam Carving on Stanford dogs dataset");
define("_PUZZLE69_DESC", "In the previous Notebook, we saw the benefit of the Seam Carving on the classification of an image with high Width/Height ratios. Because of this, I wanted to test the benefit of this method on a complete dataset. I took the Stanford dog breeds dataset to do this trial.");

define("_PUZZLE70_TITLE", "Simulation - p5.js - Ray tracing using Ray Marching");
define("_PUZZLE70_DESC", "Few times ago, I wanted to learn a bit about Ray tracing. I discovered the technic called Ray Marching to find the intersection of a ray on a surface. The principle being interesting, I wanted to make my own implementation with p5.js. I also proposed this as a problem in Codingame.");

define("_PUZZLE71_TITLE", "Visualisation - leaflet.js - Visualization of car accident in France");
define("_PUZZLE71_DESC", "On the government website, we have access to all records reported by the Police about car accidents. After a simple processing in Python, I took the opportunity of having this data to learn a bit about leaflet.js by doing a visualization of accidents by year and localization.");

define("_PUZZLE72_TITLE", "Recursion - Turtle - Fractals");
define("_PUZZLE72_DESC", "I wanted to improve my skill in recursion which is for me something difficult to code. To do so, I took the opportunity to practice this and learning at the same time Turtle module by drawing fractals.");

?>