<?php
// fichier de langues en francais
 
// Homepage
define("_WELCOME","Bienvenue sur <a href=\"#\" class=\"white\">nicolasmine.com</a>");

define("_MENU1_TITLE","Scripts");
define("_MENU2_TITLE","Qui suis-je ?");
define("_MENU3_TITLE","Apprendre Python");
define("_MENU4_TITLE","News");
define("_MENU5_TITLE","Divers");

define("_MENU1_DESC","Dans cette section, je vous partagerai des scripts que j'ai faits sur Jupyter Notebook avec des explications. Cependant, je ne présenterais pas les puzzles de Codingame car les entrées dépendent souvent de la sortie précédente que l'on donne. Vous pouvez néanmoins vous référez à mon <a href=\"https://github.com/Coni63\" target=\"_blank\">Github</a> mais les scripts ne sont ni commentés ni sur Notebooks");
define("_MENU2_DESC","Envie d'en savoir plus sur moi, jetez un coup d'oeil à mon CV");
define("_MENU3_DESC","Dans cette section, je vous présenterai différents contenus que j'ai découvert en apprenant Python ou la programmation en générale.");
define("_MENU4_DESC","Dans cette section, je partagerai diverses articles sur des informations ou nouveautés.");
define("_MENU5_DESC","Dans cette section, je partagerai des informations diverses (sites web, compte twitter, etc...). Soyez curieux !");

define("_SECTION_UP", "Haut de page");
define("_SECTION_DOWN", "Bas de page");

// Scripts
define("_SHOW_PUZZLE", "Voir le puzzle");
define("_SHOW_SOLUTION", "Voir la solution");
define("_DL_SOLUTION", "Télécharger le Notebook");
define("_SHOW_REPO", "Voir le Repository");
define("_SHOW_VID", "Regarder la vidéo");
define("_DL_JAR", "Télécharger le .jar");
define("_DL_SCRIPT", "Télécharger le script");

define("_TOP_SENTENCE", "Les scripts présents sur cette page sont aussi disponible sur mon <a href=\"https://github.com/Coni63\" target=\"_blank\">Github</a> mais non présentés ou sur notebook");

define("_SECTION_EASY", "Puzzle facile");
define("_SECTION_MEDIUM", "Puzzle moyen");
define("_SECTION_HARD", "Puzzle difficile");
define("_SECTION_V_HARD", "Puzzle très difficile");
define("_SECTION_COMMUNITY", "Puzzle de la Communauté");
define("_SECTION_OTHER", "Autres");

define("_TITLE_CG", _MENU1_TITLE);
define("_HEADER_CG", _MENU1_DESC);

define("_PUZZLE1_TITLE", "Encodage de Chuck Norris");
define("_PUZZLE1_DESC", "Dans ce puzzle, l'objectif est d'encoder en code \"unaire\" une phrase.");

define("_PUZZLE2_TITLE", "Défibrillateur le plus proche");
define("_PUZZLE2_DESC", "Dans ce puzzle, l'objectif est de trouver le plus proche defibrillateur d'une position connaissant toutes les positions des defibrillateurs");

define("_PUZZLE3_TITLE", "Automate Cellulaire");
define("_PUZZLE3_DESC", "Dans ce notebook, nous allons mettre en place un automate cellulaire avec un affichage graphique sur PyQT. Le système utilise est similaire au Jeu de la Vie mais en utilisant un autre pattern");

define("_PUZZLE4_TITLE", "Enveloppe Convexe");
define("_PUZZLE4_DESC", "Dans cet exercice, on va découvrir un algorithme permettant de déterminer l'enveloppe convexe d'un groupe de points.");

define("_PUZZLE5_TITLE", "Pathfinding - Algorithme de Dijkstra");
define("_PUZZLE5_DESC", "Dans cet exercice, on va explorer l'algorithme de recherche de chemins bien connu qu'est Dijkstra");

define("_PUZZLE6_TITLE", "Perceptron");
define("_PUZZLE6_DESC", "Dans ce notebook, l'exercice est de créer et entrainer l'élément élémentaire d'un Réseau de Neurones appelé Perceptron");

define("_PUZZLE7_TITLE", "Le problem du Voyageur de Commerce");
define("_PUZZLE7_DESC", "Dans ce notebook, l'objectif est de créer un algorithme génétique pour trouver une solution acceptable au problème bien connu du Voyageur de Commerce");

define("_PUZZLE8_TITLE", "Matrice Tridiagonale Aléatoire");
define("_PUZZLE8_DESC", "Ce notebook a été fait à la base pour aider quelqu'un sur le forum d'OpenClassRoom. L'objectif était d'observer le changement des vecteurs propres à cause de bruit dans une Matrice Tridiagonale");

define("_PUZZLE9_TITLE", "ML - Regression - Auto MPG Dataset");
define("_PUZZLE9_DESC", "L'objectif dans ce notebook est de créer un modèle de consommation de voiture basé sur les infos de la voiture. Le Dataset est disponible <a href=\"https://archive.ics.uci.edu/ml/datasets/auto+mpg\" target=\"_blank\">ici</a>");

define("_PUZZLE10_TITLE", "ML - Classification - Iris Dataset");
define("_PUZZLE10_DESC", "Dans ce workbook, nous allons passer au travers du Dataset Iris et mettre en place un Forest Tree Classifier pour visualiser son fonctionnement");

define("_PUZZLE11_TITLE", "ML - Tensorflow - Logistic Classification - Moons Dataset");
define("_PUZZLE11_DESC", "Dans cet exercice, l'objectif est de mettre en place un Classifieur Linéaire et Polynomial sur le Moons Dataset en utilisant Tensorflow");

define("_PUZZLE12_TITLE", "ML - Tensorflow - Exploration d'un Neural Network");
define("_PUZZLE12_DESC", "Dans ce workbook, l'objectif est de voir l'impact de certains paramètres d'un réseau de neurones ou des entrées sur le temps d'apprentissage");

define("_PUZZLE13_TITLE", "ML - Scikit Learn - Estimation de loyer");
define("_PUZZLE13_DESC", "Ce workbook présente l'exporation d'un dataset de loyer en fonction de l'arrondissement. L'exercice est issue d'un cours sur OpenClassRoom");

define("_PUZZLE14_TITLE", "ML - Scikit Learn - Kaggle - Credit Card Fraud");
define("_PUZZLE14_DESC", "Dans ce workbook, nous allons explorer un dataset très déséquilibré à propos des fraudes sur les cartes de crédits trouvé sur <a href=\"https://www.kaggle.com/dalpozz/creditcardfraud\" target=\"_blank\">Kaggle</a>. Sur ce dataset, nous verrons l'avantage de <b>l'undersampling</b> pour entrainer le PCA afin de simplifier le modèle.");

define("_PUZZLE15_TITLE", "ML - Scikit Learn / Keras - Kaggle - Human Resources Analytics");
define("_PUZZLE15_DESC", "Dans ce workbook, nous allons explorer un dataset à propos des des raisons de quitter une entreprise trouvé sur <a href=\"https://www.kaggle.com/ludobenistant/hr-analytics\" target=\"_blank\">Kaggle</a>.");

define("_PUZZLE16_TITLE", "ML - Keras - Introduction aux RNNs avec la Grammaire de Reber");
define("_PUZZLE16_DESC", "Ce workbook est une introduction aux Recurrent Neural Network utilisé pour les données \"temporelles\". Pour cette introduction, nous allons nous interesser à un dataset fait avec la grammaire de Reber");

define("_PUZZLE17_TITLE", "ML - FBProphet - Prediction du retard des vols ");
define("_PUZZLE17_DESC", "Pendant le Master de Data Science, nous devions faire un modèle capable de prédire le retard des vols des avions en fonction de divers paramètres (date/heure/aéroport/...). Durant ce projets, divers modeles ont été testés. Dans ce notebook, nous allons explorer une librairie appelé FBProphet afin de trouver une pattern dans les données temporelles.");

define("_PUZZLE18_TITLE", "ML - Scikit Learn - Test du UMAP sur le clustering d'articles");
define("_PUZZLE18_DESC", "UMAP est un tout nouveau algorithme proposé sur <a href=\"https://arxiv.org/abs/1802.03426\">Arxiv</a>. Pour le tester, une amélioration sur le clustering fait lors du projet 5 du parcours de Data Science va être testé. Pour ce faire, les articles vont être convertis dans une matrice TF-IDF, le LSA sera ensuite appliqué afin d'avoir une matrice dense puis pour finir, le KMeans sera utilisé afin de prédire les clusters. Pour la partie visualsation, le TSNE ainsi que UMAP vont être testés.");

define("_PUZZLE19_TITLE", "ML - Keras - Simulation d'un double pendule avec un RNN");
define("_PUZZLE19_DESC", "Après avoir mis en place un simulateur du double pendule, un dataset va être crée avec pour objectif d'entrainer un RNN sur celui-ci. Avec seulement quelques petits LSTM, une simulation correcte de ce systeme chaotique a été atteinte.");

define("_PUZZLE20_TITLE", "ML - Keras - Simulation d'un double pendule avec un RNN (partie 2)");
define("_PUZZLE20_DESC", "Précédemment, nous avons vu comment modelister un double pendule à l'aide d'un RNN. Pour ce faire, nous avions utilisé un model fixe (longueur des bras et leur masse). Dans ce model, nous allons essayer de faire le meme apprentissage mais avec des paramètres variables et de plus grandes amplitudes angulaires");

define("_PUZZLE21_TITLE", "ML - Keras - Classification Dataset QuickDraw avec 20 classes similaires");
define("_PUZZLE21_DESC", "Dans ce notebook, Différents CNN vont etre testé sur un dataset plus complexe que MNIST d'images faite à la main (20 classes, animaux uniquement, 28x28 en N&B). Les CNN classiques vont etre testés ainsi que les Capsule Networks avant de regarder les mauvaises classifications. On verra que ce sont souvent des erreurs lié au dessinateur...");

define("_PUZZLE22_TITLE", "ML - Numpy - Test de Neuro-Evolution au lieu de l'apprentissage par renforcement");
define("_PUZZLE22_DESC", "Dans ce notebook, l'entrainement d'un Reseau de Neurones a été remplacé par un algorithm d'évolution génétique au lieu de la back-propagation. Après analyse du modèle, un modèle linéaire a été entrainé et réussit presque aussi bien que le Réseaux de Neurones plus complexe.");

define("_PUZZLE23_TITLE", "DA - R - Exploration du classement sur Codingame");
define("_PUZZLE23_DESC", "Apprenant actuellement R, l'exploration du classement extrait du site Codingame permet de mettre en pratique divers points de la formation (modification dataset, utilisation de ggplot, et R markdown). Dans ce Notebook, nous allons donc explorer le classement et la répartition des joueurs dans celui-ci ainsi que des façons de monter rapidement dans le classement.");

define("_PUZZLE24_TITLE", "ML - Tensorflow - DeepDream vidéo");
define("_PUZZLE24_DESC", "Basé sur une playlist de Sentdex, son code a été réutilisé et légèrement modifié afin de créer une Video d'un DeepDream en utilisant le modèle \"inception\". Il n'y a pas de Notebook pour ce projet mais un readme assez complet est présent sur Github.");

define("_PUZZLE25_TITLE", "ML - Keras - Classification audio");
define("_PUZZLE25_DESC", "De facon similaire à MNIST, ce Notebook va explorer le contenu de fichiers audio de manière non supervisée puis effectuer une classification (avec des Reseaux de Neurones classiques, les CNNs et les RNNs).");

define("_PUZZLE26_TITLE", "ML - Keras - Audio Classification FMA");
define("_PUZZLE26_DESC", "Cette semaine nous allons explorer un autre dataset de musique qu'est le FMA dataset. Comme fait précédemment, nous allons essayer de mettre en place un classifieur du style de musique. Durant celui-ci, nous allons voir que le modele qui avait bien fonctionné la semaine dernière était due à de l'overfitting et qu'il ne fonctionne pas si bien qu'espéré en plus d'avoir d'autres inconvénients.");

define("_PUZZLE27_TITLE", "ML - Keras - Segmentation Audio FMA");
define("_PUZZLE27_DESC", "Après avoir testé la classification audio basé sur la reconnaissance de pattern sur la FFT du signal, une nouvelle approche par segmentation et clustering a été testé. Cette methode permet d'exploiter les données comme des données textuelles et a l'avantage d'être compatible avec toute longueur de morceaux");

define("_PUZZLE28_TITLE", "ML - Keras - Classification Audio FMA avec meta data");
define("_PUZZLE28_DESC", "Après avoir testé la classification audio basé sur la reconnaissance de pattern sur la FFT du signal ainsi que la segmentation audio, j'ai voulu tester la classification en utilisant les meta data extraites des morceaux. La part 1 fait la classification sur le small dataset equilibré et avec une seule classe et le second est une tentative sur les full dataset mais sans bon résultats.");

define("_PUZZLE29_TITLE", "ML - Comp. Kaggle - Free Sound Audio Tagging");
define("_PUZZLE29_DESC", "Pour finir avec le traitement audio, j'ai décidé de travailler sur un autre dataset issue d'un concours Kaggle où l'objectif est encore de classer des extraits audio. Comparer au dataset FMA, celui-ci est légèrement déséquilibré en terme de classe mais aussi en terme de durée. Pour faire la classification, nous allons extraire les mêmes caractéristiques que ce qui a été fait sur le dataset FMA et ajouter la durée avant la phase de modélisation. Le résultat n'est pas parfait mais atteint tout de même 74% de précision.");

define("_PUZZLE30_TITLE", "ML - Numpy + Scipy - Regression sur des données circulaires");
define("_PUZZLE30_DESC", "Au travail, j'ai fait face à une question sur la façon de trouver le meilleur cercle qui correspond à un ensemble de points mesurés en coordonnées (X, Y). Cela m'a donné l'idée d'approfondir cette question et de trouver des algorithmes (notament en utilisant Scipy) que j'ai ensuite testé et implémenté avec une syntaxe identique à sklearn");

define("_PUZZLE31_TITLE", "ML - NoSLQ + sklearn + nltk - Analyse de Sentiments sur des Tweets");
define("_PUZZLE31_DESC", "Un nouveau projet que je commence utilise l'analyse des sentiments sur les tweets. Un premier notebook est à propose de la requête de tweets et de stockage dans une base de données NoSQL. Le second tente de mettre en place un modèle simple pour prédire le sentiment d'un tweet.");

define("_PUZZLE32_TITLE", "Data Analysis - Sentiments Analysis on Tweets");
define("_PUZZLE32_DESC", "Avec le script précédent, nous avons vu comment utiliser l'API Twitter pour récupérer les tweets et effectuer une analyse des sentiments. Ce précédent script a été executé pendant le match France vs Argentine. Ce notebook est donc une analyse du sentiment pendant le match");

define("_PUZZLE33_TITLE", "AI - Resolveur de Taquin");
define("_PUZZLE33_DESC", "Un sujet légèrement différent aujourd'hui. Nous allons essayer de créer un solveur simple de Taquin en utilisant des algorithmes d'exploration de grpahes. Un BFS, un DFS puis le A * seront testés afin de trouver une solution au 3x3 Taquin (pas encore le 4x4 car il est beaucoup plus complexe)");

define("_PUZZLE34_TITLE", "DA - Python - Exploration du classement des compétitions sur Codingame");
define("_PUZZLE34_DESC", "Après une discussion sur les langages de programmation, je voulais voir le langage de programmation le plus utilisé dans l'IA en général. Après avoir extrait les données du classement des compétitions sur CodinGame, nous explorerons les résultats et essayerons de comprendre la raison de ce choix.");

define("_PUZZLE35_TITLE", "IA - Java - Algorithme génétique et asservissement PID");
define("_PUZZLE35_DESC", "Cette semaine j'ai fait un projet où je voulais créer en Java (en utilisant processing) un petit algorithme génétique capable de \"conduire\" un solide entre des portes comme dans flappy bird. Pour avoir un apprentissage rapide, la trajectoire est calculée en amont et le génome impacte les paramètres du PID et la vitesse sur l'axe X.");

define("_PUZZLE36_TITLE", "ML - Keras - Classification de pulsations cardiaques");
define("_PUZZLE36_DESC", "Dans ce Notebook, l'objectif était de refaire le modèle publié dans le papier <a href=\"https://arxiv.org/abs/1805.00794\">ArXviv 1805.00794</a>. Nous verrons également que même si le résultat est très bon, ils y a un très fort sur-apprentissage et le modèle ne peut pas être réutilisé sur d'autres ECGs.");

define("_PUZZLE37_TITLE", "AG - Java - Testeur de code");
define("_PUZZLE37_DESC", "Ce petit projet est un comparateur de 4 algorithmes permettant de trouver un code basé uniquement sur le nombre de chiffres corrects. Le premier essaye les chiffres un par un pour chaque position afin de trouver le bon. Le second est un algorithme génétique avec la \"fitness\" basée sur le nombre de chiffres corrects. Le troisière est un algorithme glouton et le dernier est un générateur aléatoire.");

define("_PUZZLE38_TITLE", "Algorithme - Java - Fractal");
define("_PUZZLE38_DESC", "Pour continuer avec la librairy \"Processing\" en Java. Je voulais apprendre à utiliser un peu l'utilisation de la souris. Pour ce faire, j'ai créer un moteur de rendu de fractals. Avec un clic gauche, vous pouvez modifier le nombre complexe utilisé dans la suite. Avec un clic droit, vous pouvez déplacer l'image et avec la molette de la souris, vous pouvez zoomer / dézoomer.");

define("_PUZZLE39_TITLE", "Android + Java - Communication par Bluetooth");
define("_PUZZLE39_DESC", "Pour ce second projet, je voulais apprendre un peu Android. L'idée était de pouvoir créer une application simple qui récupère les valeurs des capteurs du téléphone et l'envoyer à un script exécuté en Java sur mon ordinateur. Au début, je voulais pouvoir créer un petit jeu piloté par ses capteurs mais il y a trop de bruits. Cependant, j'ai réussi à comprendre comment fonctionne une application Android et comment utiliser le bluetooth (ce qui était l'objectif initial).");

define("_PUZZLE40_TITLE", "ML - FBProphet - Exploration de la qualité de l'air à Madrid");
define("_PUZZLE40_DESC", "Cette semaine, j'ai décidé de retester la librairie FBProphet sur un autre dataset avec plus de données que celui avec le retard des vols d'avions qui était seulement sur 1 an. Ce dataset est plus léger mais contient 18 années d’enregistrements sur la qualité de l’air à Madrid (prises toutes les heures sur 24 points). Cet ensemble de données est plus adapté aux modèles temporels comme celui-ci. Avec celui-ci, nous découvrirons l'impact de l'activité humaine sur la pollution.");

define("_PUZZLE41_TITLE", "IA - Tensorflow / Gym - Presentation du Q-Learning");
define("_PUZZLE41_DESC", "Dans ce Notebook, nous explorerons l'algorithme le plus simple pour apprendre une \"policy\". C'est ce qu'on appelle Q-Learning. Pour ce faire, nous commencerons par l'exemple le plus simple, qui est la recherche du plus court chemin dans un graphe. Ensuite, nous utiliserons \"gym\" pour tester ce modèle sur d'autres environnements présentant des difficultés différentes (sparse reward, large space-state, entrée/sortie continue). Cet exemple conduira à de futurs algorithmes par la suite.");

define("_PUZZLE42_TITLE", "ML - Keras/Sklearn/Gensim - Classification de recettes");
define("_PUZZLE42_DESC", "Ce Notebook est une partie du travail effectué pour participer à la compétition Kaggle \"What's Cooking\". L'objectif est de déterminer l'origine d'une recette en fonction de ses ingrédients. Dans ce notebook, nous aborderons plusieurs pré-traitements et modèles avec des résultats corrects.");

define("_PUZZLE43_TITLE", "IA - Keras/gYM - Presentation du DeepQ Network");
define("_PUZZLE43_DESC", "Lors d'un précédent script, nous avons vu les restrictions atteinte avec le Q-Learning. Une autre approche proposé par DeepMind en 2013 était de donner la tâche de l'evaluation de la Q-value à un Réseau de Neurones. Le DeepQ Network était né. Dans ce Notebook, nous aborderons le principe avec la mise en place d'un premier DQN");

define("_PUZZLE44_TITLE", "Libs - Python - Presentation de 2 librairies");
define("_PUZZLE44_DESC", "Étant bloqué dans un futur projet, je poste de moins en moins de projets. Cette semaine, je voulais partager 2 bibliothèques que j'ai trouvées et que je voulais essayer depuis pas mal de temps. Il y a TPOT qui utilise un algorithme génétique pour optimiser le pré-traitement de données et Black qui est un formateur de code pour les fichiers python.");

define("_PUZZLE45_TITLE", "Simulation - PyCUDA/Scipy - Comparatif GPU vs CPU pour le jeu de la vie de Conway");
define("_PUZZLE45_DESC", "BÀ la suite d’une discussion sur un forum, j’ai voulu tester les performances du GPU pour le calcul non matriciel. J'ai décidé de faire l'essai du jeu de la vie proposé par Conway. Dans ce notebook, nous comparerons les performances sur 3 differentes approches.");

define("_PUZZLE46_TITLE", "IA - Keras/Gym - Policy Gradient sur le Cartpole");
define("_PUZZLE46_DESC", "Une autre approche comparé au Deep-Q Network, qui prédit la futur gain attendu d’une action dans un état donné, consiste à prédire directement l’action. C'est ce qui est proposé avec le modèle \"Policy Gradient\" et c'est ce que nous allons voir dans ce notebook.");

define("_PUZZLE47_TITLE", "IA - Keras/Gym - Proximal Policy Optimization sur le Cartpole");
define("_PUZZLE47_DESC", "Depuis quelques années, le Policy Gradient est devenu plus ou moins obsolète. Un autre algorithme un peu plus complexe (mais bien plus performant) a été publié par OpenAI en 2017 appelé \"Proximal Policy Optimization\" (PPO). De par sa simplicité, il a également remplacé assez souvent le DeepQ Network. Dans ce notebook, nous allons mettre en place ce modèle sur le Cartpole.");

define("_PUZZLE48_TITLE", "Simulation Momentum Trading - Python - Preparation des données");
define("_PUZZLE48_DESC", "Dans le secteur de la finance, une technique d'optimisation des performances d'un Portefeuille est le Momentum Trading. Cette méthode a été longtemps étudiée et montre des performances bien au-dessus des placements proposés par les banques. Dans une serie de Notebooks, l'objectif sera de faire un simulateur sur un historique de placements appelé ETF et vérifier si cela est toujours vrai en 2018.");

define("_PUZZLE49_TITLE", "Simulation Momentum Trading - Python - Simulation (simpliste)");
define("_PUZZLE49_DESC", "
Précédemment, nous avons pré-traité les données des ETFs. Ce notebook a pour objectif de faire un premier modèle simpliste prenant en compte la performance pour estimer les possible bénéfices avec cette méthode. L'idée est d'avoir une validation de concept.");

define("_PUZZLE50_TITLE", "Simulation Momentum Trading - Python - Benchmark");
define("_PUZZLE50_DESC", "Dans le notebook précédent, un modèle simple a été mis en place pour vérifier que cette méthode fonctionne plus ou moins. La prochaine étape consiste à faire des simulations avec plusieurs paramètres et voir à quel point cette méthode est sûre");

define("_PUZZLE51_TITLE", "Simulation Momentum Trading - Python - LSTM");
define("_PUZZLE51_DESC", "Pour essayer d’améliorer/stabiliser la décision concernant le choix des ETFs, nous pouvons essayer d'entrainer un réseau de neurones récurrents avec des données sur les dernières semaines et prédire la performance future. C'est ce que j'ai essayé de faire sur ce dernier notebook.");

define("_PUZZLE52_TITLE", "Web-Scrapping - Python - Bot d'anniversaire");
define("_PUZZLE52_DESC", "Suite à une video de Micode, j'ai voulu faire aussi un bot sur twitter. Pour ce projet, l'extraction de dates d'anniversaires de célébrités est fait sur un site et un bot sera aussi mis en place afin de souhaiter chaque jour un joyeux anniversaire aux celebrités sur Twitter.");

define("_PUZZLE53_TITLE", "ML - Python - Estimation de pose");
define("_PUZZLE53_DESC", "Comparé aux scripts précédents, celui-ci ne contient pas de Notebook. Je n'ai créé qu'un \"pipeline\" pour traiter une vidéo via un modèle d'estimation de la pose appelé DensePose. Ce projet a été réalisé sur le clip vidéo \"Skibidi\" car celui-ci présente plusieurs défis pour le modèle (plus ou moins de personnages, costumes, mouvements rapides, ...)");

define("_PUZZLE54_TITLE", "ML - Python - Réseaux Bayésiens");
define("_PUZZLE54_DESC", "Lors d'un précédent projet, j'ai découvert ce quesont les réseaux bayésiens. Pour comprendre un peu plus, j'ai décidé de faire quelques exercices à ce sujet. Dans ce Notebook, j'ai exploré un peu dans la librairie \"pgmpy\" avec un exemple et un exercice. Après cela, j'en ai profité pour tester un générateur de mots à l'aide des chaines de Markov.");

define("_PUZZLE55_TITLE", "Simulation - Python - Problème du sac à dos multiple ");
define("_PUZZLE55_DESC", "Supposons que nous voulions assembler un ensemble de pièces. Comment pouvons-nous les arranger afin de minimiser la variation d'un critère sur la pièce produite? C’est ce que je voulais simuler avec ce Notebook en utilisant les algorithmes génétiques.");

define("_PUZZLE56_TITLE", "Apprentissage par Renforcement - Python/Tensorflow - IA pour le Démineur");
define("_PUZZLE56_DESC", "Après avoir appris le DQN et un peu de PPO, je voulais appliquer mes connaissances sur un projet de taille moyenne. Le jeu du démineur semblait bien. Cependant en le faisant, j'ai réalisé que ce n'était pas le cas car l'environnement est partiellement observable et stochastique. J'ai donc testé deux modèles: <br> -Le premier devrait prédire la probabilité qu'il y ait une bombe étant donné son voisinage (grille 5x5) <br>- Le second était le même mais sur l’ensemble de la grille. <br>Malheureusement, le résultat de la grille complète n'est pas très bon et l'autre n'est pas très pratique ...");

define("_PUZZLE57_TITLE", "Optimisation - Python - Décomposition de filtres ");
define("_PUZZLE57_DESC", "En traitement d’image, une étape assez commune est l’application de filtres de convolution. En fonction de la taille du filtre, le temps requis pour traiter une image peut prendre du temps. Dans ce notebook, nous verrons comment ce temps peut être très réduit en utilisant la décomposition de filtres");

define("_PUZZLE58_TITLE", "Optimisation - Python - Le probleme de la centifugeuse ");
define("_PUZZLE58_DESC", "Ces derniers temps, j'ai fait quelques puzzles sur Codingame et j'ai trouvé sur youtube un problème intéressant que j'ai décidé de résoudre. La solution est un fichier py uniquement car il n’y a pas grand chose à expliquer. La solution est présentée sur la vidéo ci-jointe.");

define("_PUZZLE59_TITLE", "Optimisation - Python - Solveur de Sudoku ");
define("_PUZZLE59_DESC", "J'ai trouvé sur Kaggle un dataset avec 1 million de sudoku. J'ai décidé de le télécharger pour vérifier si j'arrivais à les résoudre mais aussi essayer de comprendre ce qui les rend complexe à résoudre (pour un algorithme). 3 algorithmes seront comparés. Pour finir, les 4 sudoku les plus complexes seront testés sur ces algos.");

define("_PUZZLE60_TITLE", "NetworkX - Python - Facebook Network ");
define("_PUZZLE60_DESC", "Précédemment, j'ai découvert <a href=\"https://www.youtube.com/watch?v=MySkCFFgiRQ\">cette vidéo</a> de Michael Launay expliquant un fait assez marrant. Dans la majorité des cas, vous auruez l'impression d'avoir moins d'amis que vos mais sur Facebook. J'ai donc décidé de mettre en application une partie de ce que j'avais vu sur NetworkX pour le vérifier.");

define("_PUZZLE61_TITLE", "Cryptographie - Python - Pile ou Face Quantique ");
define("_PUZZLE61_DESC", "Sur youtube, Physics Girl a présenté un moyen de jouer à distance au jeu du Pile ou Face. Ceci utilise la lumière et la physique quantique. Cela m'a donné l'idée de commencer à apprendre un peu la cryptographie et c'est le premier notebook sur ce sujet.");

define("_PUZZLE62_TITLE", "Cryptographie - Python - RSA ");
define("_PUZZLE62_DESC", "Dans le domaine de la cryptographie, l'un des cryptages à clé asymétriques les plus courants est le RSA. Dans ce notebook, nous allons explorer cet algorithme (avec son fonctionnement et un exemple simple)");

define("_PUZZLE63_TITLE", "Cryptographie - Python - Cryptographie sur Courbes Elliptiques");
define("_PUZZLE63_DESC", "Lorsque j'ai commencé à apprendre la cryptographie, j'ai découvert la cryptographie sur courbes elliptiques. Cela m'a vraiment étonné avec la possibilité d'utiliser principe de l’exponentiation rapide sur des géométries. Dans ce Noteboook, nous allons donc voir le principe de l'échange de clés Diffie-Hellman, mais également la mise en œuvre d'ECC pour générer des clés");

define("_PUZZLE64_TITLE", "Cryptographie - Python - Chiffrement par bloc");
define("_PUZZLE64_DESC", "Précedemment, nous avons découvert comment créer des clés symétriques et asymétriques. Cela a été utilisé avec des méthodes de cryptage très basiques par la suite. Dans ce notebook, nous verrons comment chiffrer tout types de données. Il existe de nombreuses solutions cependant nous ne testerons que les 2 modes les plus sûrs (CBC et CTR) avec les 2 algorithmes de cryptage symmetriques les plus sûrs (AES et Triple DES).");

define("_PUZZLE65_TITLE", "Cryptographie - Python - Attaque sur le Logarithme Discret");
define("_PUZZLE65_DESC", "Dans les premiers Notebooks sur la cryptographie, nous avons parlé de la création de clé et la taille des clés nécessaires. Dans ce Notebook, nous verrons comment attaquer une clé publique pour trouver la clé privée et pouvoir déchiffrer les messages.");

define("_PUZZLE66_TITLE", "Image Preprocessing - Python - Seam Carving");
define("_PUZZLE66_DESC", "Lors d'un puzzle Codingame, j'ai découvert l'algorithme du Seam Carving qui pourrait être une très bonne solution pour le pre-processing des images dans un projet de Machine Learning. Il permettrait de redimenssionner les images sans les deformer comme c'est le cas dans la grande majorité des cas");

define("_PUZZLE67_TITLE", "Classification d'images - Keras - Class Activation Map");
define("_PUZZLE67_DESC", "Lors d'une précédente compétition Kaggle, j'ai découvert le principe de la carte d'activation de classe (CAM) pour visualiser les zones importantes pour la prédiction du modèle. Après la découverte liée à l’impact de la texture sur la classification, je voulais utiliser cette methode sur cette image (et d'autres) dans un seul Notebook");

define("_PUZZLE68_TITLE", "Classification d'images - Keras - Preparation avec Seam Carving");
define("_PUZZLE68_DESC", "Précédemment, nous avons vu une technique utilisée pour redimensionner une image sans perdre la zone d'intérêt et également visualiser quelle partie d'une image est utilisée pour effectuer la classification. Dasn ce Notebook, nous allons tester l’utilisation de Seam Carving sur de grandes images au lieu du redimensionnement classique et voir l’impact sur la classification.");

define("_PUZZLE69_TITLE", "Classification d'images - Keras - Stanford dogs dataset avec Seam Carving");
define("_PUZZLE69_DESC", "Dans le prédécent Notebook, nous avons vu l'intérêt du Seam Carving sur la classification d'images avec des ratios Largeur/Hauteur important. De ce fait, j'ai voulu tester le bénéfice de cette méthode sur un dataset complet. J'ai donc pris le dataset sur la classification des races de chiens qui possède des images assez grandes.");

define("_PUZZLE70_TITLE", "Simulation - p5.js - Ray tracing avec le Ray Marching");
define("_PUZZLE70_DESC", "Il y a quelques temps, je me suis intéressé au Ray Tracing. J'ai découvert la technique appelée Ray Marching pour trouver l'intersection d'un rayon sur une surface. Le principe étant intéressant, j'ai fais un implémentation avec p5.js. J'ai aussi proposé cela comme un problème dans Codingame.");

define("_PUZZLE71_TITLE", "Visualisation - leaflet.js - Visualisation des accidents de la route en France");
define("_PUZZLE71_DESC", "Sur le site Web du gouvernement, nous avons accès à tous les accidents de la route signalés par la police. Après un traitement simple en Python, j’ai saisi l’opportunité d'avoir ces données afin d'apprendre utilisation de leaflet.js en faisant une visualisation des accidents par année et par localisation.");

define("_PUZZLE72_TITLE", "Récursion - Turtle - Fractales");
define("_PUZZLE72_DESC", "Je voulais améliorer mes compétences en récursion, ce qui est pour moi quelque chose de difficile à coder. Pour ce faire, j'ai saisi l'occasion de le pratiquer tout en apprennant le module Tortue pour dessiner des fractales.");

?>